//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dDistrict.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dDistrict"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="р-н"/&gt;
 *     &lt;enumeration value="у"/&gt;
 *     &lt;enumeration value="тер"/&gt;
 *     &lt;enumeration value="АО"/&gt;
 *     &lt;enumeration value="п"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dDistrict")
@XmlEnum
public enum DDistrict {


    /**
     * Район
     * 
     */
    @XmlEnumValue("\u0440-\u043d")
    Р_Н("\u0440-\u043d"),

    /**
     * Улус
     * 
     */
    @XmlEnumValue("\u0443")
    У("\u0443"),

    /**
     * Территория
     * 
     */
    @XmlEnumValue("\u0442\u0435\u0440")
    ТЕР("\u0442\u0435\u0440"),

    /**
     * Автономный округ
     * 
     */
    АО("\u0410\u041e"),

    /**
     * Поселение
     * 
     */
    @XmlEnumValue("\u043f")
    П("\u043f");
    private final String value;

    DDistrict(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DDistrict fromValue(String v) {
        for (DDistrict c: DDistrict.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
