//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dInhabitedLocalities.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dInhabitedLocalities"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="аал"/&gt;
 *     &lt;enumeration value="аул"/&gt;
 *     &lt;enumeration value="волость"/&gt;
 *     &lt;enumeration value="высел"/&gt;
 *     &lt;enumeration value="г"/&gt;
 *     &lt;enumeration value="д"/&gt;
 *     &lt;enumeration value="дп"/&gt;
 *     &lt;enumeration value="ж/д_будка"/&gt;
 *     &lt;enumeration value="ж/д_казарм"/&gt;
 *     &lt;enumeration value="ж/д_оп"/&gt;
 *     &lt;enumeration value="ж/д_пост"/&gt;
 *     &lt;enumeration value="ж/д_рзд"/&gt;
 *     &lt;enumeration value="ж/д_ст"/&gt;
 *     &lt;enumeration value="заимка"/&gt;
 *     &lt;enumeration value="казарма"/&gt;
 *     &lt;enumeration value="кп"/&gt;
 *     &lt;enumeration value="м"/&gt;
 *     &lt;enumeration value="мкр"/&gt;
 *     &lt;enumeration value="нп"/&gt;
 *     &lt;enumeration value="остров"/&gt;
 *     &lt;enumeration value="п"/&gt;
 *     &lt;enumeration value="п/р"/&gt;
 *     &lt;enumeration value="п/ст"/&gt;
 *     &lt;enumeration value="пгт"/&gt;
 *     &lt;enumeration value="починок"/&gt;
 *     &lt;enumeration value="п/о"/&gt;
 *     &lt;enumeration value="промзона"/&gt;
 *     &lt;enumeration value="рзд"/&gt;
 *     &lt;enumeration value="рп"/&gt;
 *     &lt;enumeration value="с"/&gt;
 *     &lt;enumeration value="сл"/&gt;
 *     &lt;enumeration value="ст"/&gt;
 *     &lt;enumeration value="ст-ца"/&gt;
 *     &lt;enumeration value="у"/&gt;
 *     &lt;enumeration value="х"/&gt;
 *     &lt;enumeration value="городок"/&gt;
 *     &lt;enumeration value="тер"/&gt;
 *     &lt;enumeration value="ж/д_платф"/&gt;
 *     &lt;enumeration value="кв-л"/&gt;
 *     &lt;enumeration value="арбан"/&gt;
 *     &lt;enumeration value="снт"/&gt;
 *     &lt;enumeration value="лпх"/&gt;
 *     &lt;enumeration value="погост"/&gt;
 *     &lt;enumeration value="кордон"/&gt;
 *     &lt;enumeration value="автодорога"/&gt;
 *     &lt;enumeration value="жилрайон"/&gt;
 *     &lt;enumeration value="жилзона"/&gt;
 *     &lt;enumeration value="массив"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dInhabitedLocalities")
@XmlEnum
public enum DInhabitedLocalities {


    /**
     * Аал
     * 
     */
    @XmlEnumValue("\u0430\u0430\u043b")
    ААЛ("\u0430\u0430\u043b"),

    /**
     * Аул
     * 
     */
    @XmlEnumValue("\u0430\u0443\u043b")
    АУЛ("\u0430\u0443\u043b"),

    /**
     * Волость
     * 
     */
    @XmlEnumValue("\u0432\u043e\u043b\u043e\u0441\u0442\u044c")
    ВОЛОСТЬ("\u0432\u043e\u043b\u043e\u0441\u0442\u044c"),

    /**
     * Выселки(ок)
     * 
     */
    @XmlEnumValue("\u0432\u044b\u0441\u0435\u043b")
    ВЫСЕЛ("\u0432\u044b\u0441\u0435\u043b"),

    /**
     * Город
     * 
     */
    @XmlEnumValue("\u0433")
    Г("\u0433"),

    /**
     * Деревня
     * 
     */
    @XmlEnumValue("\u0434")
    Д("\u0434"),

    /**
     * Дачный посёлок
     * 
     */
    @XmlEnumValue("\u0434\u043f")
    ДП("\u0434\u043f"),

    /**
     * Железнодорожная будка
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u0431\u0443\u0434\u043a\u0430")
    Ж_Д_БУДКА("\u0436/\u0434_\u0431\u0443\u0434\u043a\u0430"),

    /**
     * Железнодорожная казарма
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u043a\u0430\u0437\u0430\u0440\u043c")
    Ж_Д_КАЗАРМ("\u0436/\u0434_\u043a\u0430\u0437\u0430\u0440\u043c"),

    /**
     * ж/д остановочный (обгонный) пункт
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u043e\u043f")
    Ж_Д_ОП("\u0436/\u0434_\u043e\u043f"),

    /**
     * Железнодорожный пост
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u043f\u043e\u0441\u0442")
    Ж_Д_ПОСТ("\u0436/\u0434_\u043f\u043e\u0441\u0442"),

    /**
     * Железнодорожный разъезд
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u0440\u0437\u0434")
    Ж_Д_РЗД("\u0436/\u0434_\u0440\u0437\u0434"),

    /**
     * Железнодорожная станция
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u0441\u0442")
    Ж_Д_СТ("\u0436/\u0434_\u0441\u0442"),

    /**
     * Заимка
     * 
     */
    @XmlEnumValue("\u0437\u0430\u0438\u043c\u043a\u0430")
    ЗАИМКА("\u0437\u0430\u0438\u043c\u043a\u0430"),

    /**
     * Казарма
     * 
     */
    @XmlEnumValue("\u043a\u0430\u0437\u0430\u0440\u043c\u0430")
    КАЗАРМА("\u043a\u0430\u0437\u0430\u0440\u043c\u0430"),

    /**
     * Курортный посёлок
     * 
     */
    @XmlEnumValue("\u043a\u043f")
    КП("\u043a\u043f"),

    /**
     * Местечко
     * 
     */
    @XmlEnumValue("\u043c")
    М("\u043c"),

    /**
     * Микрорайон
     * 
     */
    @XmlEnumValue("\u043c\u043a\u0440")
    МКР("\u043c\u043a\u0440"),

    /**
     * Населённый пункт
     * 
     */
    @XmlEnumValue("\u043d\u043f")
    НП("\u043d\u043f"),

    /**
     * Остров
     * 
     */
    @XmlEnumValue("\u043e\u0441\u0442\u0440\u043e\u0432")
    ОСТРОВ("\u043e\u0441\u0442\u0440\u043e\u0432"),

    /**
     * Посёлок
     * 
     */
    @XmlEnumValue("\u043f")
    П("\u043f"),

    /**
     * Планировочный район
     * 
     */
    @XmlEnumValue("\u043f/\u0440")
    П_Р("\u043f/\u0440"),

    /**
     * Посёлок и(при) станция(и)
     * 
     */
    @XmlEnumValue("\u043f/\u0441\u0442")
    П_СТ("\u043f/\u0441\u0442"),

    /**
     * Посёлок городского типа
     * 
     */
    @XmlEnumValue("\u043f\u0433\u0442")
    ПГТ("\u043f\u0433\u0442"),

    /**
     * Починок
     * 
     */
    @XmlEnumValue("\u043f\u043e\u0447\u0438\u043d\u043e\u043a")
    ПОЧИНОК("\u043f\u043e\u0447\u0438\u043d\u043e\u043a"),

    /**
     * Почтовое отделение
     * 
     */
    @XmlEnumValue("\u043f/\u043e")
    П_О("\u043f/\u043e"),

    /**
     * Промышленная зона
     * 
     */
    @XmlEnumValue("\u043f\u0440\u043e\u043c\u0437\u043e\u043d\u0430")
    ПРОМЗОНА("\u043f\u0440\u043e\u043c\u0437\u043e\u043d\u0430"),

    /**
     * Разъезд
     * 
     */
    @XmlEnumValue("\u0440\u0437\u0434")
    РЗД("\u0440\u0437\u0434"),

    /**
     * Рабочий посёлок
     * 
     */
    @XmlEnumValue("\u0440\u043f")
    РП("\u0440\u043f"),

    /**
     * Село
     * 
     */
    @XmlEnumValue("\u0441")
    С("\u0441"),

    /**
     * Слобода
     * 
     */
    @XmlEnumValue("\u0441\u043b")
    СЛ("\u0441\u043b"),

    /**
     * Станция
     * 
     */
    @XmlEnumValue("\u0441\u0442")
    СТ("\u0441\u0442"),

    /**
     * Станица
     * 
     */
    @XmlEnumValue("\u0441\u0442-\u0446\u0430")
    СТ_ЦА("\u0441\u0442-\u0446\u0430"),

    /**
     * Улус
     * 
     */
    @XmlEnumValue("\u0443")
    У("\u0443"),

    /**
     * Хутор
     * 
     */
    @XmlEnumValue("\u0445")
    Х("\u0445"),

    /**
     * Городок
     * 
     */
    @XmlEnumValue("\u0433\u043e\u0440\u043e\u0434\u043e\u043a")
    ГОРОДОК("\u0433\u043e\u0440\u043e\u0434\u043e\u043a"),

    /**
     * Территория
     * 
     */
    @XmlEnumValue("\u0442\u0435\u0440")
    ТЕР("\u0442\u0435\u0440"),

    /**
     * Железнодорожная платформа
     * 
     */
    @XmlEnumValue("\u0436/\u0434_\u043f\u043b\u0430\u0442\u0444")
    Ж_Д_ПЛАТФ("\u0436/\u0434_\u043f\u043b\u0430\u0442\u0444"),

    /**
     * Квартал
     * 
     */
    @XmlEnumValue("\u043a\u0432-\u043b")
    КВ_Л("\u043a\u0432-\u043b"),

    /**
     * Арбан
     * 
     */
    @XmlEnumValue("\u0430\u0440\u0431\u0430\u043d")
    АРБАН("\u0430\u0440\u0431\u0430\u043d"),

    /**
     * Садовое некоммерческое товарищество
     * 
     */
    @XmlEnumValue("\u0441\u043d\u0442")
    СНТ("\u0441\u043d\u0442"),

    /**
     * Леспромхоз
     * 
     */
    @XmlEnumValue("\u043b\u043f\u0445")
    ЛПХ("\u043b\u043f\u0445"),

    /**
     * Погост
     * 
     */
    @XmlEnumValue("\u043f\u043e\u0433\u043e\u0441\u0442")
    ПОГОСТ("\u043f\u043e\u0433\u043e\u0441\u0442"),

    /**
     * Кордон
     * 
     */
    @XmlEnumValue("\u043a\u043e\u0440\u0434\u043e\u043d")
    КОРДОН("\u043a\u043e\u0440\u0434\u043e\u043d"),

    /**
     * Автодорога
     * 
     */
    @XmlEnumValue("\u0430\u0432\u0442\u043e\u0434\u043e\u0440\u043e\u0433\u0430")
    АВТОДОРОГА("\u0430\u0432\u0442\u043e\u0434\u043e\u0440\u043e\u0433\u0430"),

    /**
     * Жилой район
     * 
     */
    @XmlEnumValue("\u0436\u0438\u043b\u0440\u0430\u0439\u043e\u043d")
    ЖИЛРАЙОН("\u0436\u0438\u043b\u0440\u0430\u0439\u043e\u043d"),

    /**
     * Жилая зона
     * 
     */
    @XmlEnumValue("\u0436\u0438\u043b\u0437\u043e\u043d\u0430")
    ЖИЛЗОНА("\u0436\u0438\u043b\u0437\u043e\u043d\u0430"),

    /**
     * Массив
     * 
     */
    @XmlEnumValue("\u043c\u0430\u0441\u0441\u0438\u0432")
    МАССИВ("\u043c\u0430\u0441\u0441\u0438\u0432");
    private final String value;

    DInhabitedLocalities(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DInhabitedLocalities fromValue(String v) {
        for (DInhabitedLocalities c: DInhabitedLocalities.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
