//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the XML.MP_v06 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttachmentRef_QNAME = new QName("", "AttachmentRef");
    private final static QName _PrimaryIdentityDocument_QNAME = new QName("", "PrimaryIdentityDocument");
    private final static QName _IdentityDocument_QNAME = new QName("", "IdentityDocument");
    private final static QName _PassportRF_QNAME = new QName("", "PassportRF");
    private final static QName _ForeignPassport_QNAME = new QName("", "ForeignPassport");
    private final static QName _ResidencePermitRF_QNAME = new QName("", "ResidencePermitRF");
    private final static QName _InternationalPassportRF_QNAME = new QName("", "InternationalPassportRF");
    private final static QName _MilitaryPassport_QNAME = new QName("", "MilitaryPassport");
    private final static QName _SailorPassport_QNAME = new QName("", "SailorPassport");
    private final static QName _SovietPassport_QNAME = new QName("", "SovietPassport");
    private final static QName _BirthCertificate_QNAME = new QName("", "BirthCertificate");
    private final static QName _DrivingLicenseRF_QNAME = new QName("", "DrivingLicenseRF");
    private final static QName _ReleaseCertificate_QNAME = new QName("", "ReleaseCertificate");
    private final static QName _PassportLossCertificate_QNAME = new QName("", "PassportLossCertificate");
    private final static QName _Form9Certificate_QNAME = new QName("", "Form9Certificate");
    private final static QName _TemporaryIdentityCardRF_QNAME = new QName("", "TemporaryIdentityCardRF");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: XML.MP_v06
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MP }
     * 
     */
    public MP createMP() {
        return new MP();
    }

    /**
     * Create an instance of {@link TSpelementUnitOldNew }
     * 
     */
    public TSpelementUnitOldNew createTSpelementUnitOldNew() {
        return new TSpelementUnitOldNew();
    }

    /**
     * Create an instance of {@link TRelatedParcels }
     * 
     */
    public TRelatedParcels createTRelatedParcels() {
        return new TRelatedParcels();
    }

    /**
     * Create an instance of {@link TRelatedParcels.ParcelNeighbours }
     * 
     */
    public TRelatedParcels.ParcelNeighbours createTRelatedParcelsParcelNeighbours() {
        return new TRelatedParcels.ParcelNeighbours();
    }

    /**
     * Create an instance of {@link TRelatedParcels.ParcelNeighbours.ParcelNeighbour }
     * 
     */
    public TRelatedParcels.ParcelNeighbours.ParcelNeighbour createTRelatedParcelsParcelNeighboursParcelNeighbour() {
        return new TRelatedParcels.ParcelNeighbours.ParcelNeighbour();
    }

    /**
     * Create an instance of {@link TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours }
     * 
     */
    public TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours createTRelatedParcelsParcelNeighboursParcelNeighbourOwnerNeighbours() {
        return new TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours();
    }

    /**
     * Create an instance of {@link TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours.OwnerNeighbour }
     * 
     */
    public TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours.OwnerNeighbour createTRelatedParcelsParcelNeighboursParcelNeighbourOwnerNeighboursOwnerNeighbour() {
        return new TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours.OwnerNeighbour();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel }
     * 
     */
    public TSpecifyRelatedParcel createTSpecifyRelatedParcel() {
        return new TSpecifyRelatedParcel();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel.ExistSubParcels }
     * 
     */
    public TSpecifyRelatedParcel.ExistSubParcels createTSpecifyRelatedParcelExistSubParcels() {
        return new TSpecifyRelatedParcel.ExistSubParcels();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel }
     * 
     */
    public TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel createTSpecifyRelatedParcelExistSubParcelsExistSubParcel() {
        return new TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours }
     * 
     */
    public TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours createTSpecifyRelatedParcelExistSubParcelsExistSubParcelContours() {
        return new TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours();
    }

    /**
     * Create an instance of {@link TContoursSubParcel }
     * 
     */
    public TContoursSubParcel createTContoursSubParcel() {
        return new TContoursSubParcel();
    }

    /**
     * Create an instance of {@link TInvariableSubParcel }
     * 
     */
    public TInvariableSubParcel createTInvariableSubParcel() {
        return new TInvariableSubParcel();
    }

    /**
     * Create an instance of {@link TInvariableSubParcel.Contours }
     * 
     */
    public TInvariableSubParcel.Contours createTInvariableSubParcelContours() {
        return new TInvariableSubParcel.Contours();
    }

    /**
     * Create an instance of {@link TDocumentsCartographic }
     * 
     */
    public TDocumentsCartographic createTDocumentsCartographic() {
        return new TDocumentsCartographic();
    }

    /**
     * Create an instance of {@link TMeansSurvey }
     * 
     */
    public TMeansSurvey createTMeansSurvey() {
        return new TMeansSurvey();
    }

    /**
     * Create an instance of {@link TMeansSurvey.MeanSurvey }
     * 
     */
    public TMeansSurvey.MeanSurvey createTMeansSurveyMeanSurvey() {
        return new TMeansSurvey.MeanSurvey();
    }

    /**
     * Create an instance of {@link TExistEZParcel }
     * 
     */
    public TExistEZParcel createTExistEZParcel() {
        return new TExistEZParcel();
    }

    /**
     * Create an instance of {@link TExistEZParcel.CompositionEZ }
     * 
     */
    public TExistEZParcel.CompositionEZ createTExistEZParcelCompositionEZ() {
        return new TExistEZParcel.CompositionEZ();
    }

    /**
     * Create an instance of {@link TExistEZParcel.CompositionEZ.InsertEntryParcels }
     * 
     */
    public TExistEZParcel.CompositionEZ.InsertEntryParcels createTExistEZParcelCompositionEZInsertEntryParcels() {
        return new TExistEZParcel.CompositionEZ.InsertEntryParcels();
    }

    /**
     * Create an instance of {@link TEncumbrance }
     * 
     */
    public TEncumbrance createTEncumbrance() {
        return new TEncumbrance();
    }

    /**
     * Create an instance of {@link TProvidingPassCadastralNumbers }
     * 
     */
    public TProvidingPassCadastralNumbers createTProvidingPassCadastralNumbers() {
        return new TProvidingPassCadastralNumbers();
    }

    /**
     * Create an instance of {@link TExistParcel }
     * 
     */
    public TExistParcel createTExistParcel() {
        return new TExistParcel();
    }

    /**
     * Create an instance of {@link TExistParcel.Contours }
     * 
     */
    public TExistParcel.Contours createTExistParcelContours() {
        return new TExistParcel.Contours();
    }

    /**
     * Create an instance of {@link TSpecifyParcel }
     * 
     */
    public TSpecifyParcel createTSpecifyParcel() {
        return new TSpecifyParcel();
    }

    /**
     * Create an instance of {@link TSpecifyParcel.ExistEZ }
     * 
     */
    public TSpecifyParcel.ExistEZ createTSpecifyParcelExistEZ() {
        return new TSpecifyParcel.ExistEZ();
    }

    /**
     * Create an instance of {@link TChangeParcel }
     * 
     */
    public TChangeParcel createTChangeParcel() {
        return new TChangeParcel();
    }

    /**
     * Create an instance of {@link TChangeParcel.TransformationContours }
     * 
     */
    public TChangeParcel.TransformationContours createTChangeParcelTransformationContours() {
        return new TChangeParcel.TransformationContours();
    }

    /**
     * Create an instance of {@link TNewParcel }
     * 
     */
    public TNewParcel createTNewParcel() {
        return new TNewParcel();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandOut }
     * 
     */
    public TSpelementUnitLandOut createTSpelementUnitLandOut() {
        return new TSpelementUnitLandOut();
    }

    /**
     * Create an instance of {@link TBorderLand }
     * 
     */
    public TBorderLand createTBorderLand() {
        return new TBorderLand();
    }

    /**
     * Create an instance of {@link TBorderLand.Edge }
     * 
     */
    public TBorderLand.Edge createTBorderLandEdge() {
        return new TBorderLand.Edge();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersLand }
     * 
     */
    public TEntitySpatialBordersLand createTEntitySpatialBordersLand() {
        return new TEntitySpatialBordersLand();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandInp }
     * 
     */
    public TSpelementUnitLandInp createTSpelementUnitLandInp() {
        return new TSpelementUnitLandInp();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSOut }
     * 
     */
    public TSpelementUnitOKSOut createTSpelementUnitOKSOut() {
        return new TSpelementUnitOKSOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSOut }
     * 
     */
    public TEntitySpatialOKSOut createTEntitySpatialOKSOut() {
        return new TEntitySpatialOKSOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut }
     * 
     */
    public TEntitySpatialBordersZUOut createTEntitySpatialBordersZUOut() {
        return new TEntitySpatialBordersZUOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut.Borders }
     * 
     */
    public TEntitySpatialBordersZUOut.Borders createTEntitySpatialBordersZUOutBorders() {
        return new TEntitySpatialBordersZUOut.Borders();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut.Borders.Border }
     * 
     */
    public TEntitySpatialBordersZUOut.Borders.Border createTEntitySpatialBordersZUOutBordersBorder() {
        return new TEntitySpatialBordersZUOut.Borders.Border();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUOut }
     * 
     */
    public TSpelementUnitZUOut createTSpelementUnitZUOut() {
        return new TSpelementUnitZUOut();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSInp }
     * 
     */
    public TSpelementUnitOKSInp createTSpelementUnitOKSInp() {
        return new TSpelementUnitOKSInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSInp }
     * 
     */
    public TEntitySpatialOKSInp createTEntitySpatialOKSInp() {
        return new TEntitySpatialOKSInp();
    }

    /**
     * Create an instance of {@link TBordersInp }
     * 
     */
    public TBordersInp createTBordersInp() {
        return new TBordersInp();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUInp }
     * 
     */
    public TSpelementUnitZUInp createTSpelementUnitZUInp() {
        return new TSpelementUnitZUInp();
    }

    /**
     * Create an instance of {@link TClientIdentify }
     * 
     */
    public TClientIdentify createTClientIdentify() {
        return new TClientIdentify();
    }

    /**
     * Create an instance of {@link TGeneralCadastralWorks }
     * 
     */
    public TGeneralCadastralWorks createTGeneralCadastralWorks() {
        return new TGeneralCadastralWorks();
    }

    /**
     * Create an instance of {@link TAppendix }
     * 
     */
    public TAppendix createTAppendix() {
        return new TAppendix();
    }

    /**
     * Create an instance of {@link MP.NodalPointSchemes }
     * 
     */
    public MP.NodalPointSchemes createMPNodalPointSchemes() {
        return new MP.NodalPointSchemes();
    }

    /**
     * Create an instance of {@link MP.Survey }
     * 
     */
    public MP.Survey createMPSurvey() {
        return new MP.Survey();
    }

    /**
     * Create an instance of {@link MP.Survey.TochnAreaSubParcels }
     * 
     */
    public MP.Survey.TochnAreaSubParcels createMPSurveyTochnAreaSubParcels() {
        return new MP.Survey.TochnAreaSubParcels();
    }

    /**
     * Create an instance of {@link MP.Survey.TochnAreaParcels }
     * 
     */
    public MP.Survey.TochnAreaParcels createMPSurveyTochnAreaParcels() {
        return new MP.Survey.TochnAreaParcels();
    }

    /**
     * Create an instance of {@link MP.Survey.GeopointsOpred }
     * 
     */
    public MP.Survey.GeopointsOpred createMPSurveyGeopointsOpred() {
        return new MP.Survey.GeopointsOpred();
    }

    /**
     * Create an instance of {@link MP.Survey.GeopointsOpred.GeopointOpred }
     * 
     */
    public MP.Survey.GeopointsOpred.GeopointOpred createMPSurveyGeopointsOpredGeopointOpred() {
        return new MP.Survey.GeopointsOpred.GeopointOpred();
    }

    /**
     * Create an instance of {@link MP.InputData }
     * 
     */
    public MP.InputData createMPInputData() {
        return new MP.InputData();
    }

    /**
     * Create an instance of {@link MP.InputData.SubParcels }
     * 
     */
    public MP.InputData.SubParcels createMPInputDataSubParcels() {
        return new MP.InputData.SubParcels();
    }

    /**
     * Create an instance of {@link MP.InputData.ObjectsRealty }
     * 
     */
    public MP.InputData.ObjectsRealty createMPInputDataObjectsRealty() {
        return new MP.InputData.ObjectsRealty();
    }

    /**
     * Create an instance of {@link MP.Package }
     * 
     */
    public MP.Package createMPPackage() {
        return new MP.Package();
    }

    /**
     * Create an instance of {@link AttachmentRefType }
     * 
     */
    public AttachmentRefType createAttachmentRefType() {
        return new AttachmentRefType();
    }

    /**
     * Create an instance of {@link PrimaryIdentityDocumentType }
     * 
     */
    public PrimaryIdentityDocumentType createPrimaryIdentityDocumentType() {
        return new PrimaryIdentityDocumentType();
    }

    /**
     * Create an instance of {@link AnyIdentityDocumentType }
     * 
     */
    public AnyIdentityDocumentType createAnyIdentityDocumentType() {
        return new AnyIdentityDocumentType();
    }

    /**
     * Create an instance of {@link PassportRFType }
     * 
     */
    public PassportRFType createPassportRFType() {
        return new PassportRFType();
    }

    /**
     * Create an instance of {@link NotRestrictedDocumentType }
     * 
     */
    public NotRestrictedDocumentType createNotRestrictedDocumentType() {
        return new NotRestrictedDocumentType();
    }

    /**
     * Create an instance of {@link InternationalPassportRFType }
     * 
     */
    public InternationalPassportRFType createInternationalPassportRFType() {
        return new InternationalPassportRFType();
    }

    /**
     * Create an instance of {@link MilitaryPassportDocumentType }
     * 
     */
    public MilitaryPassportDocumentType createMilitaryPassportDocumentType() {
        return new MilitaryPassportDocumentType();
    }

    /**
     * Create an instance of {@link SovietPassportType }
     * 
     */
    public SovietPassportType createSovietPassportType() {
        return new SovietPassportType();
    }

    /**
     * Create an instance of {@link DrivingLicenseRFType }
     * 
     */
    public DrivingLicenseRFType createDrivingLicenseRFType() {
        return new DrivingLicenseRFType();
    }

    /**
     * Create an instance of {@link MP.GeneralCadastralWorks }
     * 
     */
    public MP.GeneralCadastralWorks createMPGeneralCadastralWorks() {
        return new MP.GeneralCadastralWorks();
    }

    /**
     * Create an instance of {@link TCoordSystems }
     * 
     */
    public TCoordSystems createTCoordSystems() {
        return new TCoordSystems();
    }

    /**
     * Create an instance of {@link TAppliedFilePDF }
     * 
     */
    public TAppliedFilePDF createTAppliedFilePDF() {
        return new TAppliedFilePDF();
    }

    /**
     * Create an instance of {@link TDocumentWithoutAppliedFile }
     * 
     */
    public TDocumentWithoutAppliedFile createTDocumentWithoutAppliedFile() {
        return new TDocumentWithoutAppliedFile();
    }

    /**
     * Create an instance of {@link TDocumentAndAppliedFile }
     * 
     */
    public TDocumentAndAppliedFile createTDocumentAndAppliedFile() {
        return new TDocumentAndAppliedFile();
    }

    /**
     * Create an instance of {@link TDocumentAndPDF }
     * 
     */
    public TDocumentAndPDF createTDocumentAndPDF() {
        return new TDocumentAndPDF();
    }

    /**
     * Create an instance of {@link TAppliedFilesJPEG }
     * 
     */
    public TAppliedFilesJPEG createTAppliedFilesJPEG() {
        return new TAppliedFilesJPEG();
    }

    /**
     * Create an instance of {@link TAppliedFileJPEG }
     * 
     */
    public TAppliedFileJPEG createTAppliedFileJPEG() {
        return new TAppliedFileJPEG();
    }

    /**
     * Create an instance of {@link TAppliedFileXML }
     * 
     */
    public TAppliedFileXML createTAppliedFileXML() {
        return new TAppliedFileXML();
    }

    /**
     * Create an instance of {@link TAppliedFile }
     * 
     */
    public TAppliedFile createTAppliedFile() {
        return new TAppliedFile();
    }

    /**
     * Create an instance of {@link TAppliedFileZIP }
     * 
     */
    public TAppliedFileZIP createTAppliedFileZIP() {
        return new TAppliedFileZIP();
    }

    /**
     * Create an instance of {@link TAddressInp }
     * 
     */
    public TAddressInp createTAddressInp() {
        return new TAddressInp();
    }

    /**
     * Create an instance of {@link TAddressInpFull }
     * 
     */
    public TAddressInpFull createTAddressInpFull() {
        return new TAddressInpFull();
    }

    /**
     * Create an instance of {@link TAddressInpFullExt }
     * 
     */
    public TAddressInpFullExt createTAddressInpFullExt() {
        return new TAddressInpFullExt();
    }

    /**
     * Create an instance of {@link TAddressInpFullOKS }
     * 
     */
    public TAddressInpFullOKS createTAddressInpFullOKS() {
        return new TAddressInpFullOKS();
    }

    /**
     * Create an instance of {@link TDistrict }
     * 
     */
    public TDistrict createTDistrict() {
        return new TDistrict();
    }

    /**
     * Create an instance of {@link TCity }
     * 
     */
    public TCity createTCity() {
        return new TCity();
    }

    /**
     * Create an instance of {@link TUrbanDistrict }
     * 
     */
    public TUrbanDistrict createTUrbanDistrict() {
        return new TUrbanDistrict();
    }

    /**
     * Create an instance of {@link TSovietVillage }
     * 
     */
    public TSovietVillage createTSovietVillage() {
        return new TSovietVillage();
    }

    /**
     * Create an instance of {@link TLocality }
     * 
     */
    public TLocality createTLocality() {
        return new TLocality();
    }

    /**
     * Create an instance of {@link TStreet }
     * 
     */
    public TStreet createTStreet() {
        return new TStreet();
    }

    /**
     * Create an instance of {@link TLevel1 }
     * 
     */
    public TLevel1 createTLevel1() {
        return new TLevel1();
    }

    /**
     * Create an instance of {@link TLevel2 }
     * 
     */
    public TLevel2 createTLevel2() {
        return new TLevel2();
    }

    /**
     * Create an instance of {@link TLevel3 }
     * 
     */
    public TLevel3 createTLevel3() {
        return new TLevel3();
    }

    /**
     * Create an instance of {@link TApartment }
     * 
     */
    public TApartment createTApartment() {
        return new TApartment();
    }

    /**
     * Create an instance of {@link TEngineer }
     * 
     */
    public TEngineer createTEngineer() {
        return new TEngineer();
    }

    /**
     * Create an instance of {@link TCadastralEngineer }
     * 
     */
    public TCadastralEngineer createTCadastralEngineer() {
        return new TCadastralEngineer();
    }

    /**
     * Create an instance of {@link TOrganization }
     * 
     */
    public TOrganization createTOrganization() {
        return new TOrganization();
    }

    /**
     * Create an instance of {@link TIdentify }
     * 
     */
    public TIdentify createTIdentify() {
        return new TIdentify();
    }

    /**
     * Create an instance of {@link TOldNumber }
     * 
     */
    public TOldNumber createTOldNumber() {
        return new TOldNumber();
    }

    /**
     * Create an instance of {@link TOldNumbers }
     * 
     */
    public TOldNumbers createTOldNumbers() {
        return new TOldNumbers();
    }

    /**
     * Create an instance of {@link TOldNumberExt }
     * 
     */
    public TOldNumberExt createTOldNumberExt() {
        return new TOldNumberExt();
    }

    /**
     * Create an instance of {@link TOldNumbersExt }
     * 
     */
    public TOldNumbersExt createTOldNumbersExt() {
        return new TOldNumbersExt();
    }

    /**
     * Create an instance of {@link TCoordSystem }
     * 
     */
    public TCoordSystem createTCoordSystem() {
        return new TCoordSystem();
    }

    /**
     * Create an instance of {@link TOrdinateInp }
     * 
     */
    public TOrdinateInp createTOrdinateInp() {
        return new TOrdinateInp();
    }

    /**
     * Create an instance of {@link TOrdinateOut }
     * 
     */
    public TOrdinateOut createTOrdinateOut() {
        return new TOrdinateOut();
    }

    /**
     * Create an instance of {@link TOrdinateXY }
     * 
     */
    public TOrdinateXY createTOrdinateXY() {
        return new TOrdinateXY();
    }

    /**
     * Create an instance of {@link TBorder }
     * 
     */
    public TBorder createTBorder() {
        return new TBorder();
    }

    /**
     * Create an instance of {@link TLength }
     * 
     */
    public TLength createTLength() {
        return new TLength();
    }

    /**
     * Create an instance of {@link TDirectionAngle }
     * 
     */
    public TDirectionAngle createTDirectionAngle() {
        return new TDirectionAngle();
    }

    /**
     * Create an instance of {@link TBordersAgreement }
     * 
     */
    public TBordersAgreement createTBordersAgreement() {
        return new TBordersAgreement();
    }

    /**
     * Create an instance of {@link TBorderAgreement }
     * 
     */
    public TBorderAgreement createTBorderAgreement() {
        return new TBorderAgreement();
    }

    /**
     * Create an instance of {@link TEntitySpatialZUInp }
     * 
     */
    public TEntitySpatialZUInp createTEntitySpatialZUInp() {
        return new TEntitySpatialZUInp();
    }

    /**
     * Create an instance of {@link TSpatialElementZUInp }
     * 
     */
    public TSpatialElementZUInp createTSpatialElementZUInp() {
        return new TSpatialElementZUInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUInp }
     * 
     */
    public TEntitySpatialBordersZUInp createTEntitySpatialBordersZUInp() {
        return new TEntitySpatialBordersZUInp();
    }

    /**
     * Create an instance of {@link TSpatialElementOKSInp }
     * 
     */
    public TSpatialElementOKSInp createTSpatialElementOKSInp() {
        return new TSpatialElementOKSInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialZUOut }
     * 
     */
    public TEntitySpatialZUOut createTEntitySpatialZUOut() {
        return new TEntitySpatialZUOut();
    }

    /**
     * Create an instance of {@link TSpatialElementZUOut }
     * 
     */
    public TSpatialElementZUOut createTSpatialElementZUOut() {
        return new TSpatialElementZUOut();
    }

    /**
     * Create an instance of {@link TCadastralNumbers }
     * 
     */
    public TCadastralNumbers createTCadastralNumbers() {
        return new TCadastralNumbers();
    }

    /**
     * Create an instance of {@link TSpatialElementOKSOut }
     * 
     */
    public TSpatialElementOKSOut createTSpatialElementOKSOut() {
        return new TSpatialElementOKSOut();
    }

    /**
     * Create an instance of {@link TEntitySpatialLandInp }
     * 
     */
    public TEntitySpatialLandInp createTEntitySpatialLandInp() {
        return new TEntitySpatialLandInp();
    }

    /**
     * Create an instance of {@link TSpatialElementLandInp }
     * 
     */
    public TSpatialElementLandInp createTSpatialElementLandInp() {
        return new TSpatialElementLandInp();
    }

    /**
     * Create an instance of {@link TEntitySpatialLandOut }
     * 
     */
    public TEntitySpatialLandOut createTEntitySpatialLandOut() {
        return new TEntitySpatialLandOut();
    }

    /**
     * Create an instance of {@link TSpatialElementLandOut }
     * 
     */
    public TSpatialElementLandOut createTSpatialElementLandOut() {
        return new TSpatialElementLandOut();
    }

    /**
     * Create an instance of {@link TUtilizationDoc }
     * 
     */
    public TUtilizationDoc createTUtilizationDoc() {
        return new TUtilizationDoc();
    }

    /**
     * Create an instance of {@link TLandUseDoc }
     * 
     */
    public TLandUseDoc createTLandUseDoc() {
        return new TLandUseDoc();
    }

    /**
     * Create an instance of {@link TCategoryDoc }
     * 
     */
    public TCategoryDoc createTCategoryDoc() {
        return new TCategoryDoc();
    }

    /**
     * Create an instance of {@link TForestUse }
     * 
     */
    public TForestUse createTForestUse() {
        return new TForestUse();
    }

    /**
     * Create an instance of {@link TObjectRealty }
     * 
     */
    public TObjectRealty createTObjectRealty() {
        return new TObjectRealty();
    }

    /**
     * Create an instance of {@link TCadastralNumberInp }
     * 
     */
    public TCadastralNumberInp createTCadastralNumberInp() {
        return new TCadastralNumberInp();
    }

    /**
     * Create an instance of {@link TCadastralNumbersInp }
     * 
     */
    public TCadastralNumbersInp createTCadastralNumbersInp() {
        return new TCadastralNumbersInp();
    }

    /**
     * Create an instance of {@link TNewEZEntryParcel }
     * 
     */
    public TNewEZEntryParcel createTNewEZEntryParcel() {
        return new TNewEZEntryParcel();
    }

    /**
     * Create an instance of {@link TExistEZEntryParcel }
     * 
     */
    public TExistEZEntryParcel createTExistEZEntryParcel() {
        return new TExistEZEntryParcel();
    }

    /**
     * Create an instance of {@link TDeleteEntryParcels }
     * 
     */
    public TDeleteEntryParcels createTDeleteEntryParcels() {
        return new TDeleteEntryParcels();
    }

    /**
     * Create an instance of {@link TInputData }
     * 
     */
    public TInputData createTInputData() {
        return new TInputData();
    }

    /**
     * Create an instance of {@link TSetOfPoint }
     * 
     */
    public TSetOfPoint createTSetOfPoint() {
        return new TSetOfPoint();
    }

    /**
     * Create an instance of {@link TGeodesicBases }
     * 
     */
    public TGeodesicBases createTGeodesicBases() {
        return new TGeodesicBases();
    }

    /**
     * Create an instance of {@link TAdditionalMap }
     * 
     */
    public TAdditionalMap createTAdditionalMap() {
        return new TAdditionalMap();
    }

    /**
     * Create an instance of {@link TTochnSurvey }
     * 
     */
    public TTochnSurvey createTTochnSurvey() {
        return new TTochnSurvey();
    }

    /**
     * Create an instance of {@link TTochnSurveySubParcel }
     * 
     */
    public TTochnSurveySubParcel createTTochnSurveySubParcel() {
        return new TTochnSurveySubParcel();
    }

    /**
     * Create an instance of {@link TSubParcel }
     * 
     */
    public TSubParcel createTSubParcel() {
        return new TSubParcel();
    }

    /**
     * Create an instance of {@link TNewSubParcel }
     * 
     */
    public TNewSubParcel createTNewSubParcel() {
        return new TNewSubParcel();
    }

    /**
     * Create an instance of {@link TExistSubParcel }
     * 
     */
    public TExistSubParcel createTExistSubParcel() {
        return new TExistSubParcel();
    }

    /**
     * Create an instance of {@link TNewContour }
     * 
     */
    public TNewContour createTNewContour() {
        return new TNewContour();
    }

    /**
     * Create an instance of {@link TExistContour }
     * 
     */
    public TExistContour createTExistContour() {
        return new TExistContour();
    }

    /**
     * Create an instance of {@link TDeleteAllBorder }
     * 
     */
    public TDeleteAllBorder createTDeleteAllBorder() {
        return new TDeleteAllBorder();
    }

    /**
     * Create an instance of {@link TArea }
     * 
     */
    public TArea createTArea() {
        return new TArea();
    }

    /**
     * Create an instance of {@link TAreaNew }
     * 
     */
    public TAreaNew createTAreaNew() {
        return new TAreaNew();
    }

    /**
     * Create an instance of {@link TAreaWithoutInaccuracy }
     * 
     */
    public TAreaWithoutInaccuracy createTAreaWithoutInaccuracy() {
        return new TAreaWithoutInaccuracy();
    }

    /**
     * Create an instance of {@link TAreaContour }
     * 
     */
    public TAreaContour createTAreaContour() {
        return new TAreaContour();
    }

    /**
     * Create an instance of {@link TSpelementUnitChangeBorder }
     * 
     */
    public TSpelementUnitChangeBorder createTSpelementUnitChangeBorder() {
        return new TSpelementUnitChangeBorder();
    }

    /**
     * Create an instance of {@link TOrdinateChangeBorder }
     * 
     */
    public TOrdinateChangeBorder createTOrdinateChangeBorder() {
        return new TOrdinateChangeBorder();
    }

    /**
     * Create an instance of {@link TEntitySpatialOldNew }
     * 
     */
    public TEntitySpatialOldNew createTEntitySpatialOldNew() {
        return new TEntitySpatialOldNew();
    }

    /**
     * Create an instance of {@link TSpatialElementOldNew }
     * 
     */
    public TSpatialElementOldNew createTSpatialElementOldNew() {
        return new TSpatialElementOldNew();
    }

    /**
     * Create an instance of {@link TSpelementUnitOldNew.NewOrdinate }
     * 
     */
    public TSpelementUnitOldNew.NewOrdinate createTSpelementUnitOldNewNewOrdinate() {
        return new TSpelementUnitOldNew.NewOrdinate();
    }

    /**
     * Create an instance of {@link TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours.OwnerNeighbour.Documents }
     * 
     */
    public TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours.OwnerNeighbour.Documents createTRelatedParcelsParcelNeighboursParcelNeighbourOwnerNeighboursOwnerNeighbourDocuments() {
        return new TRelatedParcels.ParcelNeighbours.ParcelNeighbour.OwnerNeighbours.OwnerNeighbour.Documents();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel.AllBorder }
     * 
     */
    public TSpecifyRelatedParcel.AllBorder createTSpecifyRelatedParcelAllBorder() {
        return new TSpecifyRelatedParcel.AllBorder();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel.Contours }
     * 
     */
    public TSpecifyRelatedParcel.Contours createTSpecifyRelatedParcelContours() {
        return new TSpecifyRelatedParcel.Contours();
    }

    /**
     * Create an instance of {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour }
     * 
     */
    public TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour createTSpecifyRelatedParcelExistSubParcelsExistSubParcelContoursContour() {
        return new TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour();
    }

    /**
     * Create an instance of {@link TContoursSubParcel.Contour }
     * 
     */
    public TContoursSubParcel.Contour createTContoursSubParcelContour() {
        return new TContoursSubParcel.Contour();
    }

    /**
     * Create an instance of {@link TInvariableSubParcel.Contours.Contour }
     * 
     */
    public TInvariableSubParcel.Contours.Contour createTInvariableSubParcelContoursContour() {
        return new TInvariableSubParcel.Contours.Contour();
    }

    /**
     * Create an instance of {@link TDocumentsCartographic.Document }
     * 
     */
    public TDocumentsCartographic.Document createTDocumentsCartographicDocument() {
        return new TDocumentsCartographic.Document();
    }

    /**
     * Create an instance of {@link TMeansSurvey.MeanSurvey.Registration }
     * 
     */
    public TMeansSurvey.MeanSurvey.Registration createTMeansSurveyMeanSurveyRegistration() {
        return new TMeansSurvey.MeanSurvey.Registration();
    }

    /**
     * Create an instance of {@link TExistEZParcel.SubParcels }
     * 
     */
    public TExistEZParcel.SubParcels createTExistEZParcelSubParcels() {
        return new TExistEZParcel.SubParcels();
    }

    /**
     * Create an instance of {@link TExistEZParcel.CompositionEZ.InsertEntryParcels.InsertEntryParcel }
     * 
     */
    public TExistEZParcel.CompositionEZ.InsertEntryParcels.InsertEntryParcel createTExistEZParcelCompositionEZInsertEntryParcelsInsertEntryParcel() {
        return new TExistEZParcel.CompositionEZ.InsertEntryParcels.InsertEntryParcel();
    }

    /**
     * Create an instance of {@link TEncumbrance.Documents }
     * 
     */
    public TEncumbrance.Documents createTEncumbranceDocuments() {
        return new TEncumbrance.Documents();
    }

    /**
     * Create an instance of {@link TProvidingPassCadastralNumbers.Documents }
     * 
     */
    public TProvidingPassCadastralNumbers.Documents createTProvidingPassCadastralNumbersDocuments() {
        return new TProvidingPassCadastralNumbers.Documents();
    }

    /**
     * Create an instance of {@link TExistParcel.SubParcels }
     * 
     */
    public TExistParcel.SubParcels createTExistParcelSubParcels() {
        return new TExistParcel.SubParcels();
    }

    /**
     * Create an instance of {@link TExistParcel.Contours.DeleteAllBorder }
     * 
     */
    public TExistParcel.Contours.DeleteAllBorder createTExistParcelContoursDeleteAllBorder() {
        return new TExistParcel.Contours.DeleteAllBorder();
    }

    /**
     * Create an instance of {@link TSpecifyParcel.ExistEZ.ExistEZEntryParcels }
     * 
     */
    public TSpecifyParcel.ExistEZ.ExistEZEntryParcels createTSpecifyParcelExistEZExistEZEntryParcels() {
        return new TSpecifyParcel.ExistEZ.ExistEZEntryParcels();
    }

    /**
     * Create an instance of {@link TChangeParcel.SubParcels }
     * 
     */
    public TChangeParcel.SubParcels createTChangeParcelSubParcels() {
        return new TChangeParcel.SubParcels();
    }

    /**
     * Create an instance of {@link TChangeParcel.TransformationEntryParcels }
     * 
     */
    public TChangeParcel.TransformationEntryParcels createTChangeParcelTransformationEntryParcels() {
        return new TChangeParcel.TransformationEntryParcels();
    }

    /**
     * Create an instance of {@link TChangeParcel.TransformationContours.TransformationContour }
     * 
     */
    public TChangeParcel.TransformationContours.TransformationContour createTChangeParcelTransformationContoursTransformationContour() {
        return new TChangeParcel.TransformationContours.TransformationContour();
    }

    /**
     * Create an instance of {@link TNewParcel.Address }
     * 
     */
    public TNewParcel.Address createTNewParcelAddress() {
        return new TNewParcel.Address();
    }

    /**
     * Create an instance of {@link TNewParcel.SubParcels }
     * 
     */
    public TNewParcel.SubParcels createTNewParcelSubParcels() {
        return new TNewParcel.SubParcels();
    }

    /**
     * Create an instance of {@link TNewParcel.Contours }
     * 
     */
    public TNewParcel.Contours createTNewParcelContours() {
        return new TNewParcel.Contours();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandOut.Ordinate }
     * 
     */
    public TSpelementUnitLandOut.Ordinate createTSpelementUnitLandOutOrdinate() {
        return new TSpelementUnitLandOut.Ordinate();
    }

    /**
     * Create an instance of {@link TBorderLand.Edge.Neighbours }
     * 
     */
    public TBorderLand.Edge.Neighbours createTBorderLandEdgeNeighbours() {
        return new TBorderLand.Edge.Neighbours();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersLand.Borders }
     * 
     */
    public TEntitySpatialBordersLand.Borders createTEntitySpatialBordersLandBorders() {
        return new TEntitySpatialBordersLand.Borders();
    }

    /**
     * Create an instance of {@link TSpelementUnitLandInp.Ordinate }
     * 
     */
    public TSpelementUnitLandInp.Ordinate createTSpelementUnitLandInpOrdinate() {
        return new TSpelementUnitLandInp.Ordinate();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSOut.Ordinate }
     * 
     */
    public TSpelementUnitOKSOut.Ordinate createTSpelementUnitOKSOutOrdinate() {
        return new TSpelementUnitOKSOut.Ordinate();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSOut.SpatialElement }
     * 
     */
    public TEntitySpatialOKSOut.SpatialElement createTEntitySpatialOKSOutSpatialElement() {
        return new TEntitySpatialOKSOut.SpatialElement();
    }

    /**
     * Create an instance of {@link TEntitySpatialBordersZUOut.Borders.Border.Edge }
     * 
     */
    public TEntitySpatialBordersZUOut.Borders.Border.Edge createTEntitySpatialBordersZUOutBordersBorderEdge() {
        return new TEntitySpatialBordersZUOut.Borders.Border.Edge();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUOut.Ordinate }
     * 
     */
    public TSpelementUnitZUOut.Ordinate createTSpelementUnitZUOutOrdinate() {
        return new TSpelementUnitZUOut.Ordinate();
    }

    /**
     * Create an instance of {@link TSpelementUnitOKSInp.Ordinate }
     * 
     */
    public TSpelementUnitOKSInp.Ordinate createTSpelementUnitOKSInpOrdinate() {
        return new TSpelementUnitOKSInp.Ordinate();
    }

    /**
     * Create an instance of {@link TEntitySpatialOKSInp.SpatialElement }
     * 
     */
    public TEntitySpatialOKSInp.SpatialElement createTEntitySpatialOKSInpSpatialElement() {
        return new TEntitySpatialOKSInp.SpatialElement();
    }

    /**
     * Create an instance of {@link TBordersInp.Border }
     * 
     */
    public TBordersInp.Border createTBordersInpBorder() {
        return new TBordersInp.Border();
    }

    /**
     * Create an instance of {@link TSpelementUnitZUInp.Ordinate }
     * 
     */
    public TSpelementUnitZUInp.Ordinate createTSpelementUnitZUInpOrdinate() {
        return new TSpelementUnitZUInp.Ordinate();
    }

    /**
     * Create an instance of {@link TClientIdentify.Person }
     * 
     */
    public TClientIdentify.Person createTClientIdentifyPerson() {
        return new TClientIdentify.Person();
    }

    /**
     * Create an instance of {@link TClientIdentify.ForeignOrganization }
     * 
     */
    public TClientIdentify.ForeignOrganization createTClientIdentifyForeignOrganization() {
        return new TClientIdentify.ForeignOrganization();
    }

    /**
     * Create an instance of {@link TGeneralCadastralWorks.Clients }
     * 
     */
    public TGeneralCadastralWorks.Clients createTGeneralCadastralWorksClients() {
        return new TGeneralCadastralWorks.Clients();
    }

    /**
     * Create an instance of {@link TAppendix.AppliedFiles }
     * 
     */
    public TAppendix.AppliedFiles createTAppendixAppliedFiles() {
        return new TAppendix.AppliedFiles();
    }

    /**
     * Create an instance of {@link MP.NodalPointSchemes.NodalPointScheme }
     * 
     */
    public MP.NodalPointSchemes.NodalPointScheme createMPNodalPointSchemesNodalPointScheme() {
        return new MP.NodalPointSchemes.NodalPointScheme();
    }

    /**
     * Create an instance of {@link MP.Survey.TochnGeopointsParcels }
     * 
     */
    public MP.Survey.TochnGeopointsParcels createMPSurveyTochnGeopointsParcels() {
        return new MP.Survey.TochnGeopointsParcels();
    }

    /**
     * Create an instance of {@link MP.Survey.TochnGeopointsSubParcels }
     * 
     */
    public MP.Survey.TochnGeopointsSubParcels createMPSurveyTochnGeopointsSubParcels() {
        return new MP.Survey.TochnGeopointsSubParcels();
    }

    /**
     * Create an instance of {@link MP.Survey.TochnAreaSubParcels.TochnAreaSubParcel }
     * 
     */
    public MP.Survey.TochnAreaSubParcels.TochnAreaSubParcel createMPSurveyTochnAreaSubParcelsTochnAreaSubParcel() {
        return new MP.Survey.TochnAreaSubParcels.TochnAreaSubParcel();
    }

    /**
     * Create an instance of {@link MP.Survey.TochnAreaParcels.TochnAreaParcel }
     * 
     */
    public MP.Survey.TochnAreaParcels.TochnAreaParcel createMPSurveyTochnAreaParcelsTochnAreaParcel() {
        return new MP.Survey.TochnAreaParcels.TochnAreaParcel();
    }

    /**
     * Create an instance of {@link MP.Survey.GeopointsOpred.GeopointOpred.Methods }
     * 
     */
    public MP.Survey.GeopointsOpred.GeopointOpred.Methods createMPSurveyGeopointsOpredGeopointOpredMethods() {
        return new MP.Survey.GeopointsOpred.GeopointOpred.Methods();
    }

    /**
     * Create an instance of {@link MP.InputData.SubParcels.SubParcel }
     * 
     */
    public MP.InputData.SubParcels.SubParcel createMPInputDataSubParcelsSubParcel() {
        return new MP.InputData.SubParcels.SubParcel();
    }

    /**
     * Create an instance of {@link MP.InputData.ObjectsRealty.ObjectRealty }
     * 
     */
    public MP.InputData.ObjectsRealty.ObjectRealty createMPInputDataObjectsRealtyObjectRealty() {
        return new MP.InputData.ObjectsRealty.ObjectRealty();
    }

    /**
     * Create an instance of {@link MP.Package.FormParcels }
     * 
     */
    public MP.Package.FormParcels createMPPackageFormParcels() {
        return new MP.Package.FormParcels();
    }

    /**
     * Create an instance of {@link MP.Package.SpecifyParcel }
     * 
     */
    public MP.Package.SpecifyParcel createMPPackageSpecifyParcel() {
        return new MP.Package.SpecifyParcel();
    }

    /**
     * Create an instance of {@link MP.Package.SubParcels }
     * 
     */
    public MP.Package.SubParcels createMPPackageSubParcels() {
        return new MP.Package.SubParcels();
    }

    /**
     * Create an instance of {@link MP.Package.SpecifyParcelsApproximal }
     * 
     */
    public MP.Package.SpecifyParcelsApproximal createMPPackageSpecifyParcelsApproximal() {
        return new MP.Package.SpecifyParcelsApproximal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentRefType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AttachmentRefType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "AttachmentRef")
    public JAXBElement<AttachmentRefType> createAttachmentRef(AttachmentRefType value) {
        return new JAXBElement<AttachmentRefType>(_AttachmentRef_QNAME, AttachmentRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryIdentityDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrimaryIdentityDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PrimaryIdentityDocument")
    public JAXBElement<PrimaryIdentityDocumentType> createPrimaryIdentityDocument(PrimaryIdentityDocumentType value) {
        return new JAXBElement<PrimaryIdentityDocumentType>(_PrimaryIdentityDocument_QNAME, PrimaryIdentityDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyIdentityDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyIdentityDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IdentityDocument")
    public JAXBElement<AnyIdentityDocumentType> createIdentityDocument(AnyIdentityDocumentType value) {
        return new JAXBElement<AnyIdentityDocumentType>(_IdentityDocument_QNAME, AnyIdentityDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PassportRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PassportRFType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PassportRF")
    public JAXBElement<PassportRFType> createPassportRF(PassportRFType value) {
        return new JAXBElement<PassportRFType>(_PassportRF_QNAME, PassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ForeignPassport")
    public JAXBElement<NotRestrictedDocumentType> createForeignPassport(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_ForeignPassport_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ResidencePermitRF")
    public JAXBElement<InternationalPassportRFType> createResidencePermitRF(InternationalPassportRFType value) {
        return new JAXBElement<InternationalPassportRFType>(_ResidencePermitRF_QNAME, InternationalPassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InternationalPassportRFType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "InternationalPassportRF")
    public JAXBElement<InternationalPassportRFType> createInternationalPassportRF(InternationalPassportRFType value) {
        return new JAXBElement<InternationalPassportRFType>(_InternationalPassportRF_QNAME, InternationalPassportRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "MilitaryPassport")
    public JAXBElement<MilitaryPassportDocumentType> createMilitaryPassport(MilitaryPassportDocumentType value) {
        return new JAXBElement<MilitaryPassportDocumentType>(_MilitaryPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MilitaryPassportDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SailorPassport")
    public JAXBElement<MilitaryPassportDocumentType> createSailorPassport(MilitaryPassportDocumentType value) {
        return new JAXBElement<MilitaryPassportDocumentType>(_SailorPassport_QNAME, MilitaryPassportDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SovietPassport")
    public JAXBElement<SovietPassportType> createSovietPassport(SovietPassportType value) {
        return new JAXBElement<SovietPassportType>(_SovietPassport_QNAME, SovietPassportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SovietPassportType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BirthCertificate")
    public JAXBElement<SovietPassportType> createBirthCertificate(SovietPassportType value) {
        return new JAXBElement<SovietPassportType>(_BirthCertificate_QNAME, SovietPassportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrivingLicenseRFType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DrivingLicenseRFType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "DrivingLicenseRF")
    public JAXBElement<DrivingLicenseRFType> createDrivingLicenseRF(DrivingLicenseRFType value) {
        return new JAXBElement<DrivingLicenseRFType>(_DrivingLicenseRF_QNAME, DrivingLicenseRFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ReleaseCertificate")
    public JAXBElement<NotRestrictedDocumentType> createReleaseCertificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_ReleaseCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "PassportLossCertificate")
    public JAXBElement<NotRestrictedDocumentType> createPassportLossCertificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_PassportLossCertificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Form9Certificate")
    public JAXBElement<NotRestrictedDocumentType> createForm9Certificate(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_Form9Certificate_QNAME, NotRestrictedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotRestrictedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "TemporaryIdentityCardRF")
    public JAXBElement<NotRestrictedDocumentType> createTemporaryIdentityCardRF(NotRestrictedDocumentType value) {
        return new JAXBElement<NotRestrictedDocumentType>(_TemporaryIdentityCardRF_QNAME, NotRestrictedDocumentType.class, null, value);
    }

}
