//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Адрес (описание местоположения)
 * 
 * <p>Java class for tAddressInpFull complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAddressInpFull"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}tAddressInp"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Street" type="{}tStreet" minOccurs="0"/&gt;
 *         &lt;element name="Level1" type="{}tLevel1" minOccurs="0"/&gt;
 *         &lt;element name="Level2" type="{}tLevel2" minOccurs="0"/&gt;
 *         &lt;element name="Level3" type="{}tLevel3" minOccurs="0"/&gt;
 *         &lt;element name="Apartment" type="{}tApartment" minOccurs="0"/&gt;
 *         &lt;element name="Other" type="{}s2500" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAddressInpFull", propOrder = {
    "street",
    "level1",
    "level2",
    "level3",
    "apartment",
    "other"
})
@XmlSeeAlso({
    TAddressInpFullExt.class
})
public class TAddressInpFull
    extends TAddressInp
{

    @XmlElement(name = "Street")
    protected TStreet street;
    @XmlElement(name = "Level1")
    protected TLevel1 level1;
    @XmlElement(name = "Level2")
    protected TLevel2 level2;
    @XmlElement(name = "Level3")
    protected TLevel3 level3;
    @XmlElement(name = "Apartment")
    protected TApartment apartment;
    @XmlElement(name = "Other")
    protected String other;

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link TStreet }
     *     
     */
    public TStreet getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStreet }
     *     
     */
    public void setStreet(TStreet value) {
        this.street = value;
    }

    /**
     * Gets the value of the level1 property.
     * 
     * @return
     *     possible object is
     *     {@link TLevel1 }
     *     
     */
    public TLevel1 getLevel1() {
        return level1;
    }

    /**
     * Sets the value of the level1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLevel1 }
     *     
     */
    public void setLevel1(TLevel1 value) {
        this.level1 = value;
    }

    /**
     * Gets the value of the level2 property.
     * 
     * @return
     *     possible object is
     *     {@link TLevel2 }
     *     
     */
    public TLevel2 getLevel2() {
        return level2;
    }

    /**
     * Sets the value of the level2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLevel2 }
     *     
     */
    public void setLevel2(TLevel2 value) {
        this.level2 = value;
    }

    /**
     * Gets the value of the level3 property.
     * 
     * @return
     *     possible object is
     *     {@link TLevel3 }
     *     
     */
    public TLevel3 getLevel3() {
        return level3;
    }

    /**
     * Sets the value of the level3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLevel3 }
     *     
     */
    public void setLevel3(TLevel3 value) {
        this.level3 = value;
    }

    /**
     * Gets the value of the apartment property.
     * 
     * @return
     *     possible object is
     *     {@link TApartment }
     *     
     */
    public TApartment getApartment() {
        return apartment;
    }

    /**
     * Sets the value of the apartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApartment }
     *     
     */
    public void setApartment(TApartment value) {
        this.apartment = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOther(String value) {
        this.other = value;
    }

}
