//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Адрес (описание местоположения) до уровня населённого пункта
 * 
 * <p>Java class for tAddressInp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAddressInp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OKATO" type="{}OKATOType" minOccurs="0"/&gt;
 *         &lt;element name="KLADR" type="{}sNe20"/&gt;
 *         &lt;element name="OKTMO" type="{}OKTMOType" minOccurs="0"/&gt;
 *         &lt;element name="PostalCode" type="{}PostalCodeRFType" minOccurs="0"/&gt;
 *         &lt;element name="Region" type="{}dRegionsRF"/&gt;
 *         &lt;element name="District" type="{}tDistrict" minOccurs="0"/&gt;
 *         &lt;element name="City" type="{}tCity" minOccurs="0"/&gt;
 *         &lt;element name="UrbanDistrict" type="{}tUrbanDistrict" minOccurs="0"/&gt;
 *         &lt;element name="SovietVillage" type="{}tSovietVillage" minOccurs="0"/&gt;
 *         &lt;element name="Locality" type="{}tLocality" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAddressInp", propOrder = {
    "okato",
    "kladr",
    "oktmo",
    "postalCode",
    "region",
    "district",
    "city",
    "urbanDistrict",
    "sovietVillage",
    "locality"
})
@XmlSeeAlso({
    TAddressInpFull.class
})
public class TAddressInp {

    @XmlElement(name = "OKATO")
    protected String okato;
    @XmlElement(name = "KLADR", required = true)
    protected String kladr;
    @XmlElement(name = "OKTMO")
    protected String oktmo;
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    @XmlElement(name = "Region", required = true)
    protected String region;
    @XmlElement(name = "District")
    protected TDistrict district;
    @XmlElement(name = "City")
    protected TCity city;
    @XmlElement(name = "UrbanDistrict")
    protected TUrbanDistrict urbanDistrict;
    @XmlElement(name = "SovietVillage")
    protected TSovietVillage sovietVillage;
    @XmlElement(name = "Locality")
    protected TLocality locality;

    /**
     * Gets the value of the okato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKATO() {
        return okato;
    }

    /**
     * Sets the value of the okato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKATO(String value) {
        this.okato = value;
    }

    /**
     * Gets the value of the kladr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKLADR() {
        return kladr;
    }

    /**
     * Sets the value of the kladr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKLADR(String value) {
        this.kladr = value;
    }

    /**
     * Gets the value of the oktmo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKTMO() {
        return oktmo;
    }

    /**
     * Sets the value of the oktmo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKTMO(String value) {
        this.oktmo = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link TDistrict }
     *     
     */
    public TDistrict getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDistrict }
     *     
     */
    public void setDistrict(TDistrict value) {
        this.district = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link TCity }
     *     
     */
    public TCity getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCity }
     *     
     */
    public void setCity(TCity value) {
        this.city = value;
    }

    /**
     * Gets the value of the urbanDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link TUrbanDistrict }
     *     
     */
    public TUrbanDistrict getUrbanDistrict() {
        return urbanDistrict;
    }

    /**
     * Sets the value of the urbanDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUrbanDistrict }
     *     
     */
    public void setUrbanDistrict(TUrbanDistrict value) {
        this.urbanDistrict = value;
    }

    /**
     * Gets the value of the sovietVillage property.
     * 
     * @return
     *     possible object is
     *     {@link TSovietVillage }
     *     
     */
    public TSovietVillage getSovietVillage() {
        return sovietVillage;
    }

    /**
     * Sets the value of the sovietVillage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSovietVillage }
     *     
     */
    public void setSovietVillage(TSovietVillage value) {
        this.sovietVillage = value;
    }

    /**
     * Gets the value of the locality property.
     * 
     * @return
     *     possible object is
     *     {@link TLocality }
     *     
     */
    public TLocality getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLocality }
     *     
     */
    public void setLocality(TLocality value) {
        this.locality = value;
    }

}
