//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Приложения
 * 
 * <p>Java class for tAppendix complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAppendix"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AppliedFiles" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="NumberAppendix" type="{}p10"/&gt;
 *                   &lt;element name="NameAppendix" type="{}sNe1000"/&gt;
 *                   &lt;element name="AppliedFile" type="{}tAppliedFile"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAppendix", propOrder = {
    "appliedFiles"
})
public class TAppendix {

    @XmlElement(name = "AppliedFiles", required = true)
    protected List<TAppendix.AppliedFiles> appliedFiles;

    /**
     * Gets the value of the appliedFiles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appliedFiles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliedFiles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAppendix.AppliedFiles }
     * 
     * 
     */
    public List<TAppendix.AppliedFiles> getAppliedFiles() {
        if (appliedFiles == null) {
            appliedFiles = new ArrayList<TAppendix.AppliedFiles>();
        }
        return this.appliedFiles;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NumberAppendix" type="{}p10"/&gt;
     *         &lt;element name="NameAppendix" type="{}sNe1000"/&gt;
     *         &lt;element name="AppliedFile" type="{}tAppliedFile"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numberAppendix",
        "nameAppendix",
        "appliedFile"
    })
    public static class AppliedFiles {

        @XmlElement(name = "NumberAppendix", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger numberAppendix;
        @XmlElement(name = "NameAppendix", required = true)
        protected String nameAppendix;
        @XmlElement(name = "AppliedFile", required = true)
        protected TAppliedFile appliedFile;

        /**
         * Gets the value of the numberAppendix property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberAppendix() {
            return numberAppendix;
        }

        /**
         * Sets the value of the numberAppendix property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberAppendix(BigInteger value) {
            this.numberAppendix = value;
        }

        /**
         * Gets the value of the nameAppendix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameAppendix() {
            return nameAppendix;
        }

        /**
         * Sets the value of the nameAppendix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameAppendix(String value) {
            this.nameAppendix = value;
        }

        /**
         * Gets the value of the appliedFile property.
         * 
         * @return
         *     possible object is
         *     {@link TAppliedFile }
         *     
         */
        public TAppliedFile getAppliedFile() {
            return appliedFile;
        }

        /**
         * Sets the value of the appliedFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAppliedFile }
         *     
         */
        public void setAppliedFile(TAppliedFile value) {
            this.appliedFile = value;
        }

    }

}
