//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о документах (в том числе картографических)
 * 
 * <p>Java class for tDocumentsCartographic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDocumentsCartographic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Document" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{}tDocumentAndAppliedFile"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AdditionalMap" type="{}tAdditionalMap" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDocumentsCartographic", propOrder = {
    "document"
})
public class TDocumentsCartographic {

    @XmlElement(name = "Document", required = true)
    protected List<TDocumentsCartographic.Document> document;

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDocumentsCartographic.Document }
     * 
     * 
     */
    public List<TDocumentsCartographic.Document> getDocument() {
        if (document == null) {
            document = new ArrayList<TDocumentsCartographic.Document>();
        }
        return this.document;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{}tDocumentAndAppliedFile"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AdditionalMap" type="{}tAdditionalMap" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "additionalMap"
    })
    public static class Document
        extends TDocumentAndAppliedFile
    {

        @XmlElement(name = "AdditionalMap")
        protected TAdditionalMap additionalMap;

        /**
         * Gets the value of the additionalMap property.
         * 
         * @return
         *     possible object is
         *     {@link TAdditionalMap }
         *     
         */
        public TAdditionalMap getAdditionalMap() {
            return additionalMap;
        }

        /**
         * Sets the value of the additionalMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAdditionalMap }
         *     
         */
        public void setAdditionalMap(TAdditionalMap value) {
            this.additionalMap = value;
        }

    }

}
