//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Реквизиты документа с приложенным образом в формате PDF
 * 
 * <p>Java class for tDocumentAndPDF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDocumentAndPDF"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}tDocumentWithoutAppliedFile"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AppliedFilePDF" type="{}tAppliedFilePDF" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDocumentAndPDF", propOrder = {
    "appliedFilePDF"
})
public class TDocumentAndPDF
    extends TDocumentWithoutAppliedFile
{

    @XmlElement(name = "AppliedFilePDF")
    protected TAppliedFilePDF appliedFilePDF;

    /**
     * Gets the value of the appliedFilePDF property.
     * 
     * @return
     *     possible object is
     *     {@link TAppliedFilePDF }
     *     
     */
    public TAppliedFilePDF getAppliedFilePDF() {
        return appliedFilePDF;
    }

    /**
     * Sets the value of the appliedFilePDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAppliedFilePDF }
     *     
     */
    public void setAppliedFilePDF(TAppliedFilePDF value) {
        this.appliedFilePDF = value;
    }

}
