//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Кадастровый инженер
 * 
 * <p>Java class for tEngineer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEngineer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}tCadastralEngineer"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Organization" type="{}tOrganization" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEngineer", propOrder = {
    "organization"
})
public class TEngineer
    extends TCadastralEngineer
{

    @XmlElement(name = "Organization")
    protected TOrganization organization;

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link TOrganization }
     *     
     */
    public TOrganization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOrganization }
     *     
     */
    public void setOrganization(TOrganization value) {
        this.organization = value;
    }

}
