//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Описание образуемого земельного участка и его частей
 * 
 * <p>Java class for tNewParcel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tNewParcel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CadastralBlock" type="{}CadastralBlockType"/&gt;
 *         &lt;element name="PrevCadastralNumbers" type="{}tCadastralNumbersInp" minOccurs="0"/&gt;
 *         &lt;element name="ProvidingPassCadastralNumbers" type="{}tProvidingPassCadastralNumbers" minOccurs="0"/&gt;
 *         &lt;element name="ObjectRealty" type="{}tObjectRealty" minOccurs="0"/&gt;
 *         &lt;element name="Area" type="{}tAreaNew"/&gt;
 *         &lt;element name="Address"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{}tAddressInpFullExt"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Document" type="{}tDocumentAndPDF" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Category" type="{}tCategoryDoc"/&gt;
 *         &lt;element name="NaturalObject" type="{}tForestUse" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Utilization" type="{}tUtilizationDoc"/&gt;
 *           &lt;element name="LandUse" type="{}tLandUseDoc"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="SubParcels" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="NewSubParcel" type="{}tNewSubParcel" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Contours"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="NewContour" type="{}tNewContour" maxOccurs="unbounded"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="EntitySpatial" type="{}tEntitySpatialBordersZUInp"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="MinArea" type="{}tAreaWithoutInaccuracy" minOccurs="0"/&gt;
 *         &lt;element name="MaxArea" type="{}tAreaWithoutInaccuracy" minOccurs="0"/&gt;
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RelatedParcels" type="{}tRelatedParcels" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Definition" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{}s50"&gt;
 *             &lt;pattern value="(\d{2}:\d{2}:\d{6,7}:\d{1,})?:ЗУ\d{1,}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tNewParcel", propOrder = {
    "cadastralBlock",
    "prevCadastralNumbers",
    "providingPassCadastralNumbers",
    "objectRealty",
    "area",
    "address",
    "category",
    "naturalObject",
    "utilization",
    "landUse",
    "subParcels",
    "contours",
    "entitySpatial",
    "minArea",
    "maxArea",
    "note",
    "relatedParcels"
})
public class TNewParcel {

    @XmlElement(name = "CadastralBlock", required = true)
    protected String cadastralBlock;
    @XmlElement(name = "PrevCadastralNumbers")
    protected TCadastralNumbersInp prevCadastralNumbers;
    @XmlElement(name = "ProvidingPassCadastralNumbers")
    protected TProvidingPassCadastralNumbers providingPassCadastralNumbers;
    @XmlElement(name = "ObjectRealty")
    protected TObjectRealty objectRealty;
    @XmlElement(name = "Area", required = true)
    protected TAreaNew area;
    @XmlElement(name = "Address", required = true)
    protected TNewParcel.Address address;
    @XmlElement(name = "Category", required = true)
    protected TCategoryDoc category;
    @XmlElement(name = "NaturalObject")
    protected TForestUse naturalObject;
    @XmlElement(name = "Utilization")
    protected TUtilizationDoc utilization;
    @XmlElement(name = "LandUse")
    protected TLandUseDoc landUse;
    @XmlElement(name = "SubParcels")
    protected TNewParcel.SubParcels subParcels;
    @XmlElement(name = "Contours")
    protected TNewParcel.Contours contours;
    @XmlElement(name = "EntitySpatial")
    protected TEntitySpatialBordersZUInp entitySpatial;
    @XmlElement(name = "MinArea")
    protected TAreaWithoutInaccuracy minArea;
    @XmlElement(name = "MaxArea")
    protected TAreaWithoutInaccuracy maxArea;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "RelatedParcels")
    protected TRelatedParcels relatedParcels;
    @XmlAttribute(name = "Definition", required = true)
    protected String definition;

    /**
     * Gets the value of the cadastralBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadastralBlock() {
        return cadastralBlock;
    }

    /**
     * Sets the value of the cadastralBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadastralBlock(String value) {
        this.cadastralBlock = value;
    }

    /**
     * Gets the value of the prevCadastralNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link TCadastralNumbersInp }
     *     
     */
    public TCadastralNumbersInp getPrevCadastralNumbers() {
        return prevCadastralNumbers;
    }

    /**
     * Sets the value of the prevCadastralNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCadastralNumbersInp }
     *     
     */
    public void setPrevCadastralNumbers(TCadastralNumbersInp value) {
        this.prevCadastralNumbers = value;
    }

    /**
     * Gets the value of the providingPassCadastralNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link TProvidingPassCadastralNumbers }
     *     
     */
    public TProvidingPassCadastralNumbers getProvidingPassCadastralNumbers() {
        return providingPassCadastralNumbers;
    }

    /**
     * Sets the value of the providingPassCadastralNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProvidingPassCadastralNumbers }
     *     
     */
    public void setProvidingPassCadastralNumbers(TProvidingPassCadastralNumbers value) {
        this.providingPassCadastralNumbers = value;
    }

    /**
     * Gets the value of the objectRealty property.
     * 
     * @return
     *     possible object is
     *     {@link TObjectRealty }
     *     
     */
    public TObjectRealty getObjectRealty() {
        return objectRealty;
    }

    /**
     * Sets the value of the objectRealty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TObjectRealty }
     *     
     */
    public void setObjectRealty(TObjectRealty value) {
        this.objectRealty = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link TAreaNew }
     *     
     */
    public TAreaNew getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAreaNew }
     *     
     */
    public void setArea(TAreaNew value) {
        this.area = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link TNewParcel.Address }
     *     
     */
    public TNewParcel.Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNewParcel.Address }
     *     
     */
    public void setAddress(TNewParcel.Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link TCategoryDoc }
     *     
     */
    public TCategoryDoc getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCategoryDoc }
     *     
     */
    public void setCategory(TCategoryDoc value) {
        this.category = value;
    }

    /**
     * Gets the value of the naturalObject property.
     * 
     * @return
     *     possible object is
     *     {@link TForestUse }
     *     
     */
    public TForestUse getNaturalObject() {
        return naturalObject;
    }

    /**
     * Sets the value of the naturalObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link TForestUse }
     *     
     */
    public void setNaturalObject(TForestUse value) {
        this.naturalObject = value;
    }

    /**
     * Gets the value of the utilization property.
     * 
     * @return
     *     possible object is
     *     {@link TUtilizationDoc }
     *     
     */
    public TUtilizationDoc getUtilization() {
        return utilization;
    }

    /**
     * Sets the value of the utilization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUtilizationDoc }
     *     
     */
    public void setUtilization(TUtilizationDoc value) {
        this.utilization = value;
    }

    /**
     * Gets the value of the landUse property.
     * 
     * @return
     *     possible object is
     *     {@link TLandUseDoc }
     *     
     */
    public TLandUseDoc getLandUse() {
        return landUse;
    }

    /**
     * Sets the value of the landUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLandUseDoc }
     *     
     */
    public void setLandUse(TLandUseDoc value) {
        this.landUse = value;
    }

    /**
     * Gets the value of the subParcels property.
     * 
     * @return
     *     possible object is
     *     {@link TNewParcel.SubParcels }
     *     
     */
    public TNewParcel.SubParcels getSubParcels() {
        return subParcels;
    }

    /**
     * Sets the value of the subParcels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNewParcel.SubParcels }
     *     
     */
    public void setSubParcels(TNewParcel.SubParcels value) {
        this.subParcels = value;
    }

    /**
     * Gets the value of the contours property.
     * 
     * @return
     *     possible object is
     *     {@link TNewParcel.Contours }
     *     
     */
    public TNewParcel.Contours getContours() {
        return contours;
    }

    /**
     * Sets the value of the contours property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNewParcel.Contours }
     *     
     */
    public void setContours(TNewParcel.Contours value) {
        this.contours = value;
    }

    /**
     * Gets the value of the entitySpatial property.
     * 
     * @return
     *     possible object is
     *     {@link TEntitySpatialBordersZUInp }
     *     
     */
    public TEntitySpatialBordersZUInp getEntitySpatial() {
        return entitySpatial;
    }

    /**
     * Sets the value of the entitySpatial property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEntitySpatialBordersZUInp }
     *     
     */
    public void setEntitySpatial(TEntitySpatialBordersZUInp value) {
        this.entitySpatial = value;
    }

    /**
     * Gets the value of the minArea property.
     * 
     * @return
     *     possible object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public TAreaWithoutInaccuracy getMinArea() {
        return minArea;
    }

    /**
     * Sets the value of the minArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public void setMinArea(TAreaWithoutInaccuracy value) {
        this.minArea = value;
    }

    /**
     * Gets the value of the maxArea property.
     * 
     * @return
     *     possible object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public TAreaWithoutInaccuracy getMaxArea() {
        return maxArea;
    }

    /**
     * Sets the value of the maxArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public void setMaxArea(TAreaWithoutInaccuracy value) {
        this.maxArea = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the relatedParcels property.
     * 
     * @return
     *     possible object is
     *     {@link TRelatedParcels }
     *     
     */
    public TRelatedParcels getRelatedParcels() {
        return relatedParcels;
    }

    /**
     * Sets the value of the relatedParcels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRelatedParcels }
     *     
     */
    public void setRelatedParcels(TRelatedParcels value) {
        this.relatedParcels = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{}tAddressInpFullExt"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Document" type="{}tDocumentAndPDF" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "document"
    })
    public static class Address
        extends TAddressInpFullExt
    {

        @XmlElement(name = "Document")
        protected TDocumentAndPDF document;

        /**
         * Gets the value of the document property.
         * 
         * @return
         *     possible object is
         *     {@link TDocumentAndPDF }
         *     
         */
        public TDocumentAndPDF getDocument() {
            return document;
        }

        /**
         * Sets the value of the document property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDocumentAndPDF }
         *     
         */
        public void setDocument(TDocumentAndPDF value) {
            this.document = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NewContour" type="{}tNewContour" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "newContour"
    })
    public static class Contours {

        @XmlElement(name = "NewContour", required = true)
        protected List<TNewContour> newContour;

        /**
         * Gets the value of the newContour property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the newContour property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNewContour().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TNewContour }
         * 
         * 
         */
        public List<TNewContour> getNewContour() {
            if (newContour == null) {
                newContour = new ArrayList<TNewContour>();
            }
            return this.newContour;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NewSubParcel" type="{}tNewSubParcel" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "newSubParcel"
    })
    public static class SubParcels {

        @XmlElement(name = "NewSubParcel", required = true)
        protected List<TNewSubParcel> newSubParcel;

        /**
         * Gets the value of the newSubParcel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the newSubParcel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNewSubParcel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TNewSubParcel }
         * 
         * 
         */
        public List<TNewSubParcel> getNewSubParcel() {
            if (newSubParcel == null) {
                newSubParcel = new ArrayList<TNewSubParcel>();
            }
            return this.newSubParcel;
        }

    }

}
