//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.06 at 12:22:20 PM MSK 
//


package XML.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о виде использования участка в соответствии с ранее использовавшимся классификатором dUtilizations Сборника классификаторов, сведения о разрешенном использовании в соответствии с документом, реквизиты документа, устанавливающего вид разрешенного использования земельного участка
 * 
 * <p>Java class for tUtilizationDoc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tUtilizationDoc"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocUtilization" type="{}tDocumentAndPDF" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Utilization" type="{}dUtilizations" /&gt;
 *       &lt;attribute name="ByDoc" type="{}s4000" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tUtilizationDoc", propOrder = {
    "docUtilization"
})
public class TUtilizationDoc {

    @XmlElement(name = "DocUtilization")
    protected TDocumentAndPDF docUtilization;
    @XmlAttribute(name = "Utilization")
    protected String utilization;
    @XmlAttribute(name = "ByDoc")
    protected String byDoc;

    /**
     * Gets the value of the docUtilization property.
     * 
     * @return
     *     possible object is
     *     {@link TDocumentAndPDF }
     *     
     */
    public TDocumentAndPDF getDocUtilization() {
        return docUtilization;
    }

    /**
     * Sets the value of the docUtilization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDocumentAndPDF }
     *     
     */
    public void setDocUtilization(TDocumentAndPDF value) {
        this.docUtilization = value;
    }

    /**
     * Gets the value of the utilization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtilization() {
        return utilization;
    }

    /**
     * Sets the value of the utilization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtilization(String value) {
        this.utilization = value;
    }

    /**
     * Gets the value of the byDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByDoc() {
        return byDoc;
    }

    /**
     * Sets the value of the byDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByDoc(String value) {
        this.byDoc = value;
    }

}
