//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dCity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dCity"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="г"/&gt;
 *     &lt;enumeration value="пгт"/&gt;
 *     &lt;enumeration value="рп"/&gt;
 *     &lt;enumeration value="кп"/&gt;
 *     &lt;enumeration value="дп"/&gt;
 *     &lt;enumeration value="с/с"/&gt;
 *     &lt;enumeration value="с/а"/&gt;
 *     &lt;enumeration value="с/о"/&gt;
 *     &lt;enumeration value="волость"/&gt;
 *     &lt;enumeration value="п/о"/&gt;
 *     &lt;enumeration value="тер"/&gt;
 *     &lt;enumeration value="с/п"/&gt;
 *     &lt;enumeration value="с/мо"/&gt;
 *     &lt;enumeration value="массив"/&gt;
 *     &lt;enumeration value="п"/&gt;
 *     &lt;enumeration value="местность"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dCity")
@XmlEnum
public enum DCity {


    /**
     * Город
     * 
     */
    @XmlEnumValue("\u0433")
    Г("\u0433"),

    /**
     * Посёлок городского типа
     * 
     */
    @XmlEnumValue("\u043f\u0433\u0442")
    ПГТ("\u043f\u0433\u0442"),

    /**
     * Рабочий посёлок
     * 
     */
    @XmlEnumValue("\u0440\u043f")
    РП("\u0440\u043f"),

    /**
     * Курортный посёлок
     * 
     */
    @XmlEnumValue("\u043a\u043f")
    КП("\u043a\u043f"),

    /**
     * Дачный посёлок
     * 
     */
    @XmlEnumValue("\u0434\u043f")
    ДП("\u0434\u043f"),

    /**
     * Сельсовет
     * 
     */
    @XmlEnumValue("\u0441/\u0441")
    С_С("\u0441/\u0441"),

    /**
     * Сельская администрация
     * 
     */
    @XmlEnumValue("\u0441/\u0430")
    С_А("\u0441/\u0430"),

    /**
     * Сельский округ
     * 
     */
    @XmlEnumValue("\u0441/\u043e")
    С_О("\u0441/\u043e"),

    /**
     * Волость
     * 
     */
    @XmlEnumValue("\u0432\u043e\u043b\u043e\u0441\u0442\u044c")
    ВОЛОСТЬ("\u0432\u043e\u043b\u043e\u0441\u0442\u044c"),

    /**
     * Почтовое отделение
     * 
     */
    @XmlEnumValue("\u043f/\u043e")
    П_О("\u043f/\u043e"),

    /**
     * Территория
     * 
     */
    @XmlEnumValue("\u0442\u0435\u0440")
    ТЕР("\u0442\u0435\u0440"),

    /**
     * Сельское поселение
     * 
     */
    @XmlEnumValue("\u0441/\u043f")
    С_П("\u0441/\u043f"),

    /**
     * Сельское муниципальное образование
     * 
     */
    @XmlEnumValue("\u0441/\u043c\u043e")
    С_МО("\u0441/\u043c\u043e"),

    /**
     * Массив
     * 
     */
    @XmlEnumValue("\u043c\u0430\u0441\u0441\u0438\u0432")
    МАССИВ("\u043c\u0430\u0441\u0441\u0438\u0432"),

    /**
     * Посёлок
     * 
     */
    @XmlEnumValue("\u043f")
    П("\u043f"),

    /**
     * Местность
     * 
     */
    @XmlEnumValue("\u043c\u0435\u0441\u0442\u043d\u043e\u0441\u0442\u044c")
    МЕСТНОСТЬ("\u043c\u0435\u0441\u0442\u043d\u043e\u0441\u0442\u044c");
    private final String value;

    DCity(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DCity fromValue(String v) {
        for (DCity c: DCity.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
