//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dLocationLevel2Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dLocationLevel2Type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="корп"/&gt;
 *     &lt;enumeration value="д"/&gt;
 *     &lt;enumeration value="уч"/&gt;
 *     &lt;enumeration value="вл"/&gt;
 *     &lt;enumeration value="гараж"/&gt;
 *     &lt;enumeration value="бокс"/&gt;
 *     &lt;enumeration value="строение"/&gt;
 *     &lt;enumeration value="сооружение"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "dLocationLevel2Type")
@XmlEnum
public enum DLocationLevel2Type {


    /**
     * Корпус
     * 
     */
    @XmlEnumValue("\u043a\u043e\u0440\u043f")
    КОРП("\u043a\u043e\u0440\u043f"),

    /**
     * Дом
     * 
     */
    @XmlEnumValue("\u0434")
    Д("\u0434"),

    /**
     * Участок
     * 
     */
    @XmlEnumValue("\u0443\u0447")
    УЧ("\u0443\u0447"),

    /**
     * Владение
     * 
     */
    @XmlEnumValue("\u0432\u043b")
    ВЛ("\u0432\u043b"),

    /**
     * Гараж
     * 
     */
    @XmlEnumValue("\u0433\u0430\u0440\u0430\u0436")
    ГАРАЖ("\u0433\u0430\u0440\u0430\u0436"),

    /**
     * бокс
     * 
     */
    @XmlEnumValue("\u0431\u043e\u043a\u0441")
    БОКС("\u0431\u043e\u043a\u0441"),

    /**
     * строение
     * 
     */
    @XmlEnumValue("\u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0435")
    СТРОЕНИЕ("\u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0435"),

    /**
     * сооружение
     * 
     */
    @XmlEnumValue("\u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u0435")
    СООРУЖЕНИЕ("\u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u0435");
    private final String value;

    DLocationLevel2Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DLocationLevel2Type fromValue(String v) {
        for (DLocationLevel2Type c: DLocationLevel2Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
