//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сведения о заказчике кадастровых работ
 * 
 * <p>Java class for tClientIdentify complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tClientIdentify"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Person"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;group ref="{}PhysicalPersonQualifiedName-ModelGroup"/&gt;
 *                   &lt;choice&gt;
 *                     &lt;element name="SNILS" type="{}SNILSType"/&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element name="Address" type="{}tAddressInpFull"/&gt;
 *                       &lt;element name="Document" type="{}tDocumentWithoutAppliedFile"/&gt;
 *                     &lt;/sequence&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Organization" type="{}tIdentify"/&gt;
 *         &lt;element name="Governance" type="{}tIdentify"/&gt;
 *         &lt;element name="ForeignOrganization"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{}tIdentify"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Country" type="{}sNe255"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tClientIdentify", propOrder = {
    "person",
    "organization",
    "governance",
    "foreignOrganization"
})
public class TClientIdentify {

    @XmlElement(name = "Person")
    protected TClientIdentify.Person person;
    @XmlElement(name = "Organization")
    protected TIdentify organization;
    @XmlElement(name = "Governance")
    protected TIdentify governance;
    @XmlElement(name = "ForeignOrganization")
    protected TClientIdentify.ForeignOrganization foreignOrganization;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link TClientIdentify.Person }
     *     
     */
    public TClientIdentify.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClientIdentify.Person }
     *     
     */
    public void setPerson(TClientIdentify.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentify }
     *     
     */
    public TIdentify getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentify }
     *     
     */
    public void setOrganization(TIdentify value) {
        this.organization = value;
    }

    /**
     * Gets the value of the governance property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentify }
     *     
     */
    public TIdentify getGovernance() {
        return governance;
    }

    /**
     * Sets the value of the governance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentify }
     *     
     */
    public void setGovernance(TIdentify value) {
        this.governance = value;
    }

    /**
     * Gets the value of the foreignOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link TClientIdentify.ForeignOrganization }
     *     
     */
    public TClientIdentify.ForeignOrganization getForeignOrganization() {
        return foreignOrganization;
    }

    /**
     * Sets the value of the foreignOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClientIdentify.ForeignOrganization }
     *     
     */
    public void setForeignOrganization(TClientIdentify.ForeignOrganization value) {
        this.foreignOrganization = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{}tIdentify"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Country" type="{}sNe255"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "country"
    })
    public static class ForeignOrganization
        extends TIdentify
    {

        @XmlElement(name = "Country", required = true)
        protected String country;

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;group ref="{}PhysicalPersonQualifiedName-ModelGroup"/&gt;
     *         &lt;choice&gt;
     *           &lt;element name="SNILS" type="{}SNILSType"/&gt;
     *           &lt;sequence&gt;
     *             &lt;element name="Address" type="{}tAddressInpFull"/&gt;
     *             &lt;element name="Document" type="{}tDocumentWithoutAppliedFile"/&gt;
     *           &lt;/sequence&gt;
     *         &lt;/choice&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "familyName",
        "firstName",
        "patronymic",
        "snils",
        "address",
        "document"
    })
    public static class Person {

        @XmlElement(name = "FamilyName", required = true)
        protected String familyName;
        @XmlElement(name = "FirstName", required = true)
        protected String firstName;
        @XmlElement(name = "Patronymic")
        protected String patronymic;
        @XmlElement(name = "SNILS")
        protected String snils;
        @XmlElement(name = "Address")
        protected TAddressInpFull address;
        @XmlElement(name = "Document")
        protected TDocumentWithoutAppliedFile document;

        /**
         * Gets the value of the familyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFamilyName() {
            return familyName;
        }

        /**
         * Sets the value of the familyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFamilyName(String value) {
            this.familyName = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the patronymic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatronymic() {
            return patronymic;
        }

        /**
         * Sets the value of the patronymic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatronymic(String value) {
            this.patronymic = value;
        }

        /**
         * Gets the value of the snils property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSNILS() {
            return snils;
        }

        /**
         * Sets the value of the snils property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSNILS(String value) {
            this.snils = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link TAddressInpFull }
         *     
         */
        public TAddressInpFull getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAddressInpFull }
         *     
         */
        public void setAddress(TAddressInpFull value) {
            this.address = value;
        }

        /**
         * Gets the value of the document property.
         * 
         * @return
         *     possible object is
         *     {@link TDocumentWithoutAppliedFile }
         *     
         */
        public TDocumentWithoutAppliedFile getDocument() {
            return document;
        }

        /**
         * Sets the value of the document property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDocumentWithoutAppliedFile }
         *     
         */
        public void setDocument(TDocumentWithoutAppliedFile value) {
            this.document = value;
        }

    }

}
