//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Описание элементов контура (характерных точек контура) земельного участка, части земельного участка
 * 
 * <p>Java class for tEntitySpatialZUOut complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEntitySpatialZUOut"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SpatialElement" type="{}tSpatialElementZUOut" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="EntSys" use="required" type="{}sIDREF255" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEntitySpatialZUOut", propOrder = {
    "spatialElement"
})
@XmlSeeAlso({
    TEntitySpatialBordersZUOut.class
})
public class TEntitySpatialZUOut {

    @XmlElement(name = "SpatialElement", required = true)
    protected List<TSpatialElementZUOut> spatialElement;
    @XmlAttribute(name = "EntSys", required = true)
    @XmlIDREF
    protected Object entSys;

    /**
     * Gets the value of the spatialElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatialElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpatialElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSpatialElementZUOut }
     * 
     * 
     */
    public List<TSpatialElementZUOut> getSpatialElement() {
        if (spatialElement == null) {
            spatialElement = new ArrayList<TSpatialElementZUOut>();
        }
        return this.spatialElement;
    }

    /**
     * Gets the value of the entSys property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEntSys() {
        return entSys;
    }

    /**
     * Sets the value of the entSys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEntSys(Object value) {
        this.entSys = value;
    }

}
