//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Описание уточняемого земельного участка, не являющегося единым землепользованием (и его частей)
 * 
 * <p>Java class for tExistParcel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tExistParcel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CadastralBlock" type="{}CadastralBlockType"/&gt;
 *         &lt;element name="ObjectRealty" type="{}tObjectRealty" minOccurs="0"/&gt;
 *         &lt;element name="Area" type="{}tAreaNew"/&gt;
 *         &lt;element name="SubParcels" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="NewSubParcel" type="{}tNewSubParcel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="ExistSubParcel" type="{}tExistSubParcel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="InvariableSubParcel" type="{}tInvariableSubParcel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;choice&gt;
 *           &lt;element name="EntitySpatial" type="{}tEntitySpatialOldNew"/&gt;
 *           &lt;element name="Contours"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="NewContour" type="{}tNewContour" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                     &lt;element name="ExistContour" type="{}tExistContour" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                     &lt;element name="DeleteAllBorder" maxOccurs="unbounded" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;extension base="{}tDeleteAllBorder"&gt;
 *                             &lt;attribute name="NumberRecord" use="required" type="{}p10" /&gt;
 *                           &lt;/extension&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="AreaInGKN" type="{}nn20" minOccurs="0"/&gt;
 *         &lt;element name="DeltaArea" type="{}nn20" minOccurs="0"/&gt;
 *         &lt;element name="MinArea" type="{}tAreaWithoutInaccuracy" minOccurs="0"/&gt;
 *         &lt;element name="MaxArea" type="{}tAreaWithoutInaccuracy" minOccurs="0"/&gt;
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RelatedParcels" type="{}tRelatedParcels" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CadastralNumber" use="required" type="{}CadastralNumberType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tExistParcel", propOrder = {
    "cadastralBlock",
    "objectRealty",
    "area",
    "subParcels",
    "entitySpatial",
    "contours",
    "areaInGKN",
    "deltaArea",
    "minArea",
    "maxArea",
    "note",
    "relatedParcels"
})
public class TExistParcel {

    @XmlElement(name = "CadastralBlock", required = true)
    protected String cadastralBlock;
    @XmlElement(name = "ObjectRealty")
    protected TObjectRealty objectRealty;
    @XmlElement(name = "Area", required = true)
    protected TAreaNew area;
    @XmlElement(name = "SubParcels")
    protected TExistParcel.SubParcels subParcels;
    @XmlElement(name = "EntitySpatial")
    protected TEntitySpatialOldNew entitySpatial;
    @XmlElement(name = "Contours")
    protected TExistParcel.Contours contours;
    @XmlElement(name = "AreaInGKN")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger areaInGKN;
    @XmlElement(name = "DeltaArea")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger deltaArea;
    @XmlElement(name = "MinArea")
    protected TAreaWithoutInaccuracy minArea;
    @XmlElement(name = "MaxArea")
    protected TAreaWithoutInaccuracy maxArea;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "RelatedParcels")
    protected TRelatedParcels relatedParcels;
    @XmlAttribute(name = "CadastralNumber", required = true)
    protected String cadastralNumber;

    /**
     * Gets the value of the cadastralBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadastralBlock() {
        return cadastralBlock;
    }

    /**
     * Sets the value of the cadastralBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadastralBlock(String value) {
        this.cadastralBlock = value;
    }

    /**
     * Gets the value of the objectRealty property.
     * 
     * @return
     *     possible object is
     *     {@link TObjectRealty }
     *     
     */
    public TObjectRealty getObjectRealty() {
        return objectRealty;
    }

    /**
     * Sets the value of the objectRealty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TObjectRealty }
     *     
     */
    public void setObjectRealty(TObjectRealty value) {
        this.objectRealty = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link TAreaNew }
     *     
     */
    public TAreaNew getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAreaNew }
     *     
     */
    public void setArea(TAreaNew value) {
        this.area = value;
    }

    /**
     * Gets the value of the subParcels property.
     * 
     * @return
     *     possible object is
     *     {@link TExistParcel.SubParcels }
     *     
     */
    public TExistParcel.SubParcels getSubParcels() {
        return subParcels;
    }

    /**
     * Sets the value of the subParcels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExistParcel.SubParcels }
     *     
     */
    public void setSubParcels(TExistParcel.SubParcels value) {
        this.subParcels = value;
    }

    /**
     * Gets the value of the entitySpatial property.
     * 
     * @return
     *     possible object is
     *     {@link TEntitySpatialOldNew }
     *     
     */
    public TEntitySpatialOldNew getEntitySpatial() {
        return entitySpatial;
    }

    /**
     * Sets the value of the entitySpatial property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEntitySpatialOldNew }
     *     
     */
    public void setEntitySpatial(TEntitySpatialOldNew value) {
        this.entitySpatial = value;
    }

    /**
     * Gets the value of the contours property.
     * 
     * @return
     *     possible object is
     *     {@link TExistParcel.Contours }
     *     
     */
    public TExistParcel.Contours getContours() {
        return contours;
    }

    /**
     * Sets the value of the contours property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExistParcel.Contours }
     *     
     */
    public void setContours(TExistParcel.Contours value) {
        this.contours = value;
    }

    /**
     * Gets the value of the areaInGKN property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAreaInGKN() {
        return areaInGKN;
    }

    /**
     * Sets the value of the areaInGKN property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAreaInGKN(BigInteger value) {
        this.areaInGKN = value;
    }

    /**
     * Gets the value of the deltaArea property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeltaArea() {
        return deltaArea;
    }

    /**
     * Sets the value of the deltaArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeltaArea(BigInteger value) {
        this.deltaArea = value;
    }

    /**
     * Gets the value of the minArea property.
     * 
     * @return
     *     possible object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public TAreaWithoutInaccuracy getMinArea() {
        return minArea;
    }

    /**
     * Sets the value of the minArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public void setMinArea(TAreaWithoutInaccuracy value) {
        this.minArea = value;
    }

    /**
     * Gets the value of the maxArea property.
     * 
     * @return
     *     possible object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public TAreaWithoutInaccuracy getMaxArea() {
        return maxArea;
    }

    /**
     * Sets the value of the maxArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAreaWithoutInaccuracy }
     *     
     */
    public void setMaxArea(TAreaWithoutInaccuracy value) {
        this.maxArea = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the relatedParcels property.
     * 
     * @return
     *     possible object is
     *     {@link TRelatedParcels }
     *     
     */
    public TRelatedParcels getRelatedParcels() {
        return relatedParcels;
    }

    /**
     * Sets the value of the relatedParcels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRelatedParcels }
     *     
     */
    public void setRelatedParcels(TRelatedParcels value) {
        this.relatedParcels = value;
    }

    /**
     * Gets the value of the cadastralNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadastralNumber() {
        return cadastralNumber;
    }

    /**
     * Sets the value of the cadastralNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadastralNumber(String value) {
        this.cadastralNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NewContour" type="{}tNewContour" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="ExistContour" type="{}tExistContour" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="DeleteAllBorder" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{}tDeleteAllBorder"&gt;
     *                 &lt;attribute name="NumberRecord" use="required" type="{}p10" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "newContour",
        "existContour",
        "deleteAllBorder"
    })
    public static class Contours {

        @XmlElement(name = "NewContour")
        protected List<TNewContour> newContour;
        @XmlElement(name = "ExistContour")
        protected List<TExistContour> existContour;
        @XmlElement(name = "DeleteAllBorder")
        protected List<TExistParcel.Contours.DeleteAllBorder> deleteAllBorder;

        /**
         * Gets the value of the newContour property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the newContour property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNewContour().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TNewContour }
         * 
         * 
         */
        public List<TNewContour> getNewContour() {
            if (newContour == null) {
                newContour = new ArrayList<TNewContour>();
            }
            return this.newContour;
        }

        /**
         * Gets the value of the existContour property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the existContour property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExistContour().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TExistContour }
         * 
         * 
         */
        public List<TExistContour> getExistContour() {
            if (existContour == null) {
                existContour = new ArrayList<TExistContour>();
            }
            return this.existContour;
        }

        /**
         * Gets the value of the deleteAllBorder property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deleteAllBorder property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeleteAllBorder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TExistParcel.Contours.DeleteAllBorder }
         * 
         * 
         */
        public List<TExistParcel.Contours.DeleteAllBorder> getDeleteAllBorder() {
            if (deleteAllBorder == null) {
                deleteAllBorder = new ArrayList<TExistParcel.Contours.DeleteAllBorder>();
            }
            return this.deleteAllBorder;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{}tDeleteAllBorder"&gt;
         *       &lt;attribute name="NumberRecord" use="required" type="{}p10" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DeleteAllBorder
            extends TDeleteAllBorder
        {

            @XmlAttribute(name = "NumberRecord", required = true)
            protected BigInteger numberRecord;

            /**
             * Gets the value of the numberRecord property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberRecord() {
                return numberRecord;
            }

            /**
             * Sets the value of the numberRecord property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberRecord(BigInteger value) {
                this.numberRecord = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NewSubParcel" type="{}tNewSubParcel" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="ExistSubParcel" type="{}tExistSubParcel" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="InvariableSubParcel" type="{}tInvariableSubParcel" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "newSubParcel",
        "existSubParcel",
        "invariableSubParcel"
    })
    public static class SubParcels {

        @XmlElement(name = "NewSubParcel")
        protected List<TNewSubParcel> newSubParcel;
        @XmlElement(name = "ExistSubParcel")
        protected List<TExistSubParcel> existSubParcel;
        @XmlElement(name = "InvariableSubParcel")
        protected List<TInvariableSubParcel> invariableSubParcel;

        /**
         * Gets the value of the newSubParcel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the newSubParcel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNewSubParcel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TNewSubParcel }
         * 
         * 
         */
        public List<TNewSubParcel> getNewSubParcel() {
            if (newSubParcel == null) {
                newSubParcel = new ArrayList<TNewSubParcel>();
            }
            return this.newSubParcel;
        }

        /**
         * Gets the value of the existSubParcel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the existSubParcel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExistSubParcel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TExistSubParcel }
         * 
         * 
         */
        public List<TExistSubParcel> getExistSubParcel() {
            if (existSubParcel == null) {
                existSubParcel = new ArrayList<TExistSubParcel>();
            }
            return this.existSubParcel;
        }

        /**
         * Gets the value of the invariableSubParcel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invariableSubParcel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvariableSubParcel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TInvariableSubParcel }
         * 
         * 
         */
        public List<TInvariableSubParcel> getInvariableSubParcel() {
            if (invariableSubParcel == null) {
                invariableSubParcel = new ArrayList<TInvariableSubParcel>();
            }
            return this.invariableSubParcel;
        }

    }

}
