//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Исходные данные
 * 
 * <p>Java class for tInputData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tInputData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Documents" type="{}tDocumentsCartographic"/&gt;
 *         &lt;element name="GeodesicBases" type="{}tGeodesicBases" minOccurs="0"/&gt;
 *         &lt;element name="MeansSurvey" type="{}tMeansSurvey" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInputData", propOrder = {
    "documents",
    "geodesicBases",
    "meansSurvey"
})
@XmlSeeAlso({
    ga.osipov.XSD.MP_v06.MP.InputData.class
})
public class TInputData {

    @XmlElement(name = "Documents", required = true)
    protected TDocumentsCartographic documents;
    @XmlElement(name = "GeodesicBases")
    protected TGeodesicBases geodesicBases;
    @XmlElement(name = "MeansSurvey")
    protected TMeansSurvey meansSurvey;

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link TDocumentsCartographic }
     *     
     */
    public TDocumentsCartographic getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDocumentsCartographic }
     *     
     */
    public void setDocuments(TDocumentsCartographic value) {
        this.documents = value;
    }

    /**
     * Gets the value of the geodesicBases property.
     * 
     * @return
     *     possible object is
     *     {@link TGeodesicBases }
     *     
     */
    public TGeodesicBases getGeodesicBases() {
        return geodesicBases;
    }

    /**
     * Sets the value of the geodesicBases property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGeodesicBases }
     *     
     */
    public void setGeodesicBases(TGeodesicBases value) {
        this.geodesicBases = value;
    }

    /**
     * Gets the value of the meansSurvey property.
     * 
     * @return
     *     possible object is
     *     {@link TMeansSurvey }
     *     
     */
    public TMeansSurvey getMeansSurvey() {
        return meansSurvey;
    }

    /**
     * Sets the value of the meansSurvey property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMeansSurvey }
     *     
     */
    public void setMeansSurvey(TMeansSurvey value) {
        this.meansSurvey = value;
    }

}
