//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Уточнение границ смежного земельного участка (в т.ч. части участка) при образовании или уточнении границ ЗУ
 * 
 * <p>Java class for tSpecifyRelatedParcel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSpecifyRelatedParcel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="AllBorder"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="EntitySpatial" type="{}tEntitySpatialOldNew"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="ChangeBorder" type="{}tSpelementUnitChangeBorder" maxOccurs="unbounded"/&gt;
 *           &lt;element name="Contours"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="NewContour" type="{}tNewContour" maxOccurs="unbounded"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="DeleteAllBorder" type="{}tDeleteAllBorder"/&gt;
 *         &lt;/choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="ExistSubParcels" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="ExistSubParcel" maxOccurs="unbounded"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
 *                               &lt;element name="Contours"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="Contour" maxOccurs="unbounded"&gt;
 *                                           &lt;complexType&gt;
 *                                             &lt;complexContent&gt;
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                 &lt;sequence&gt;
 *                                                   &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
 *                                                 &lt;/sequence&gt;
 *                                                 &lt;attribute name="Number" use="required" type="{}p10" /&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/complexContent&gt;
 *                                           &lt;/complexType&gt;
 *                                         &lt;/element&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/choice&gt;
 *                             &lt;attribute name="NumberRecord" use="required" type="{}p10" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CadastralNumber" use="required" type="{}CadastralNumberType" /&gt;
 *       &lt;attribute name="NumberRecord" type="{}p10" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSpecifyRelatedParcel", propOrder = {
    "allBorder",
    "changeBorder",
    "contours",
    "deleteAllBorder",
    "existSubParcels"
})
public class TSpecifyRelatedParcel {

    @XmlElement(name = "AllBorder")
    protected TSpecifyRelatedParcel.AllBorder allBorder;
    @XmlElement(name = "ChangeBorder")
    protected List<TSpelementUnitChangeBorder> changeBorder;
    @XmlElement(name = "Contours")
    protected TSpecifyRelatedParcel.Contours contours;
    @XmlElement(name = "DeleteAllBorder")
    protected TDeleteAllBorder deleteAllBorder;
    @XmlElement(name = "ExistSubParcels")
    protected TSpecifyRelatedParcel.ExistSubParcels existSubParcels;
    @XmlAttribute(name = "CadastralNumber", required = true)
    protected String cadastralNumber;
    @XmlAttribute(name = "NumberRecord")
    protected BigInteger numberRecord;

    /**
     * Gets the value of the allBorder property.
     * 
     * @return
     *     possible object is
     *     {@link TSpecifyRelatedParcel.AllBorder }
     *     
     */
    public TSpecifyRelatedParcel.AllBorder getAllBorder() {
        return allBorder;
    }

    /**
     * Sets the value of the allBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSpecifyRelatedParcel.AllBorder }
     *     
     */
    public void setAllBorder(TSpecifyRelatedParcel.AllBorder value) {
        this.allBorder = value;
    }

    /**
     * Gets the value of the changeBorder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeBorder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeBorder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSpelementUnitChangeBorder }
     * 
     * 
     */
    public List<TSpelementUnitChangeBorder> getChangeBorder() {
        if (changeBorder == null) {
            changeBorder = new ArrayList<TSpelementUnitChangeBorder>();
        }
        return this.changeBorder;
    }

    /**
     * Gets the value of the contours property.
     * 
     * @return
     *     possible object is
     *     {@link TSpecifyRelatedParcel.Contours }
     *     
     */
    public TSpecifyRelatedParcel.Contours getContours() {
        return contours;
    }

    /**
     * Sets the value of the contours property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSpecifyRelatedParcel.Contours }
     *     
     */
    public void setContours(TSpecifyRelatedParcel.Contours value) {
        this.contours = value;
    }

    /**
     * Gets the value of the deleteAllBorder property.
     * 
     * @return
     *     possible object is
     *     {@link TDeleteAllBorder }
     *     
     */
    public TDeleteAllBorder getDeleteAllBorder() {
        return deleteAllBorder;
    }

    /**
     * Sets the value of the deleteAllBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDeleteAllBorder }
     *     
     */
    public void setDeleteAllBorder(TDeleteAllBorder value) {
        this.deleteAllBorder = value;
    }

    /**
     * Gets the value of the existSubParcels property.
     * 
     * @return
     *     possible object is
     *     {@link TSpecifyRelatedParcel.ExistSubParcels }
     *     
     */
    public TSpecifyRelatedParcel.ExistSubParcels getExistSubParcels() {
        return existSubParcels;
    }

    /**
     * Sets the value of the existSubParcels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSpecifyRelatedParcel.ExistSubParcels }
     *     
     */
    public void setExistSubParcels(TSpecifyRelatedParcel.ExistSubParcels value) {
        this.existSubParcels = value;
    }

    /**
     * Gets the value of the cadastralNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadastralNumber() {
        return cadastralNumber;
    }

    /**
     * Sets the value of the cadastralNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadastralNumber(String value) {
        this.cadastralNumber = value;
    }

    /**
     * Gets the value of the numberRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberRecord() {
        return numberRecord;
    }

    /**
     * Sets the value of the numberRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberRecord(BigInteger value) {
        this.numberRecord = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EntitySpatial" type="{}tEntitySpatialOldNew"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entitySpatial"
    })
    public static class AllBorder {

        @XmlElement(name = "EntitySpatial", required = true)
        protected TEntitySpatialOldNew entitySpatial;

        /**
         * Gets the value of the entitySpatial property.
         * 
         * @return
         *     possible object is
         *     {@link TEntitySpatialOldNew }
         *     
         */
        public TEntitySpatialOldNew getEntitySpatial() {
            return entitySpatial;
        }

        /**
         * Sets the value of the entitySpatial property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEntitySpatialOldNew }
         *     
         */
        public void setEntitySpatial(TEntitySpatialOldNew value) {
            this.entitySpatial = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NewContour" type="{}tNewContour" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "newContour"
    })
    public static class Contours {

        @XmlElement(name = "NewContour", required = true)
        protected List<TNewContour> newContour;

        /**
         * Gets the value of the newContour property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the newContour property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNewContour().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TNewContour }
         * 
         * 
         */
        public List<TNewContour> getNewContour() {
            if (newContour == null) {
                newContour = new ArrayList<TNewContour>();
            }
            return this.newContour;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ExistSubParcel" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
     *                   &lt;element name="Contours"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Contour" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
     *                                     &lt;/sequence&gt;
     *                                     &lt;attribute name="Number" use="required" type="{}p10" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *                 &lt;attribute name="NumberRecord" use="required" type="{}p10" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "existSubParcel"
    })
    public static class ExistSubParcels {

        @XmlElement(name = "ExistSubParcel", required = true)
        protected List<TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel> existSubParcel;

        /**
         * Gets the value of the existSubParcel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the existSubParcel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExistSubParcel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel }
         * 
         * 
         */
        public List<TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel> getExistSubParcel() {
            if (existSubParcel == null) {
                existSubParcel = new ArrayList<TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel>();
            }
            return this.existSubParcel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
         *         &lt;element name="Contours"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Contour" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
         *                           &lt;/sequence&gt;
         *                           &lt;attribute name="Number" use="required" type="{}p10" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *       &lt;attribute name="NumberRecord" use="required" type="{}p10" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entitySpatial",
            "contours"
        })
        public static class ExistSubParcel {

            @XmlElement(name = "EntitySpatial")
            protected TEntitySpatialZUInp entitySpatial;
            @XmlElement(name = "Contours")
            protected TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours contours;
            @XmlAttribute(name = "NumberRecord", required = true)
            protected BigInteger numberRecord;

            /**
             * Gets the value of the entitySpatial property.
             * 
             * @return
             *     possible object is
             *     {@link TEntitySpatialZUInp }
             *     
             */
            public TEntitySpatialZUInp getEntitySpatial() {
                return entitySpatial;
            }

            /**
             * Sets the value of the entitySpatial property.
             * 
             * @param value
             *     allowed object is
             *     {@link TEntitySpatialZUInp }
             *     
             */
            public void setEntitySpatial(TEntitySpatialZUInp value) {
                this.entitySpatial = value;
            }

            /**
             * Gets the value of the contours property.
             * 
             * @return
             *     possible object is
             *     {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours }
             *     
             */
            public TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours getContours() {
                return contours;
            }

            /**
             * Sets the value of the contours property.
             * 
             * @param value
             *     allowed object is
             *     {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours }
             *     
             */
            public void setContours(TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours value) {
                this.contours = value;
            }

            /**
             * Gets the value of the numberRecord property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberRecord() {
                return numberRecord;
            }

            /**
             * Sets the value of the numberRecord property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberRecord(BigInteger value) {
                this.numberRecord = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Contour" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="Number" use="required" type="{}p10" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "contour"
            })
            public static class Contours {

                @XmlElement(name = "Contour", required = true)
                protected List<TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour> contour;

                /**
                 * Gets the value of the contour property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the contour property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContour().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour }
                 * 
                 * 
                 */
                public List<TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour> getContour() {
                    if (contour == null) {
                        contour = new ArrayList<TSpecifyRelatedParcel.ExistSubParcels.ExistSubParcel.Contours.Contour>();
                    }
                    return this.contour;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="Number" use="required" type="{}p10" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "entitySpatial"
                })
                public static class Contour {

                    @XmlElement(name = "EntitySpatial", required = true)
                    protected TEntitySpatialZUInp entitySpatial;
                    @XmlAttribute(name = "Number", required = true)
                    protected BigInteger number;

                    /**
                     * Gets the value of the entitySpatial property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEntitySpatialZUInp }
                     *     
                     */
                    public TEntitySpatialZUInp getEntitySpatial() {
                        return entitySpatial;
                    }

                    /**
                     * Sets the value of the entitySpatial property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEntitySpatialZUInp }
                     *     
                     */
                    public void setEntitySpatial(TEntitySpatialZUInp value) {
                        this.entitySpatial = value;
                    }

                    /**
                     * Gets the value of the number property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getNumber() {
                        return number;
                    }

                    /**
                     * Sets the value of the number property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setNumber(BigInteger value) {
                        this.number = value;
                    }

                }

            }

        }

    }

}
