//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Уточнение границы одного ЗУ (являющимся либо ЕЗ либо "обычным" участком)
 * 
 * <p>Java class for tSpecifyParcel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSpecifyParcel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="ExistParcel" type="{}tExistParcel"/&gt;
 *         &lt;element name="ExistEZ"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ExistEZParcels" type="{}tExistEZParcel"/&gt;
 *                   &lt;element name="ExistEZEntryParcels" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ExistEZEntryParcel" type="{}tExistEZEntryParcel" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSpecifyParcel", propOrder = {
    "existParcel",
    "existEZ"
})
@XmlSeeAlso({
    ga.osipov.XSD.MP_v06.MP.Package.SpecifyParcel.class
})
public class TSpecifyParcel {

    @XmlElement(name = "ExistParcel")
    protected TExistParcel existParcel;
    @XmlElement(name = "ExistEZ")
    protected TSpecifyParcel.ExistEZ existEZ;

    /**
     * Gets the value of the existParcel property.
     * 
     * @return
     *     possible object is
     *     {@link TExistParcel }
     *     
     */
    public TExistParcel getExistParcel() {
        return existParcel;
    }

    /**
     * Sets the value of the existParcel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TExistParcel }
     *     
     */
    public void setExistParcel(TExistParcel value) {
        this.existParcel = value;
    }

    /**
     * Gets the value of the existEZ property.
     * 
     * @return
     *     possible object is
     *     {@link TSpecifyParcel.ExistEZ }
     *     
     */
    public TSpecifyParcel.ExistEZ getExistEZ() {
        return existEZ;
    }

    /**
     * Sets the value of the existEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSpecifyParcel.ExistEZ }
     *     
     */
    public void setExistEZ(TSpecifyParcel.ExistEZ value) {
        this.existEZ = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ExistEZParcels" type="{}tExistEZParcel"/&gt;
     *         &lt;element name="ExistEZEntryParcels" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ExistEZEntryParcel" type="{}tExistEZEntryParcel" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "existEZParcels",
        "existEZEntryParcels"
    })
    public static class ExistEZ {

        @XmlElement(name = "ExistEZParcels", required = true)
        protected TExistEZParcel existEZParcels;
        @XmlElement(name = "ExistEZEntryParcels")
        protected TSpecifyParcel.ExistEZ.ExistEZEntryParcels existEZEntryParcels;

        /**
         * Gets the value of the existEZParcels property.
         * 
         * @return
         *     possible object is
         *     {@link TExistEZParcel }
         *     
         */
        public TExistEZParcel getExistEZParcels() {
            return existEZParcels;
        }

        /**
         * Sets the value of the existEZParcels property.
         * 
         * @param value
         *     allowed object is
         *     {@link TExistEZParcel }
         *     
         */
        public void setExistEZParcels(TExistEZParcel value) {
            this.existEZParcels = value;
        }

        /**
         * Gets the value of the existEZEntryParcels property.
         * 
         * @return
         *     possible object is
         *     {@link TSpecifyParcel.ExistEZ.ExistEZEntryParcels }
         *     
         */
        public TSpecifyParcel.ExistEZ.ExistEZEntryParcels getExistEZEntryParcels() {
            return existEZEntryParcels;
        }

        /**
         * Sets the value of the existEZEntryParcels property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSpecifyParcel.ExistEZ.ExistEZEntryParcels }
         *     
         */
        public void setExistEZEntryParcels(TSpecifyParcel.ExistEZ.ExistEZEntryParcels value) {
            this.existEZEntryParcels = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ExistEZEntryParcel" type="{}tExistEZEntryParcel" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "existEZEntryParcel"
        })
        public static class ExistEZEntryParcels {

            @XmlElement(name = "ExistEZEntryParcel", required = true)
            protected List<TExistEZEntryParcel> existEZEntryParcel;

            /**
             * Gets the value of the existEZEntryParcel property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the existEZEntryParcel property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExistEZEntryParcel().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TExistEZEntryParcel }
             * 
             * 
             */
            public List<TExistEZEntryParcel> getExistEZEntryParcel() {
                if (existEZEntryParcel == null) {
                    existEZEntryParcel = new ArrayList<TExistEZEntryParcel>();
                }
                return this.existEZEntryParcel;
            }

        }

    }

}
