//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Часть участка
 * 
 * <p>Java class for tSubParcel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSubParcel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Area" type="{}tArea"/&gt;
 *         &lt;element name="Encumbrance" type="{}tEncumbrance"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="EntitySpatial" type="{}tEntitySpatialZUInp"/&gt;
 *           &lt;element name="Contours" type="{}tContoursSubParcel"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSubParcel", propOrder = {
    "area",
    "encumbrance",
    "entitySpatial",
    "contours"
})
@XmlSeeAlso({
    TNewSubParcel.class,
    TExistSubParcel.class
})
public class TSubParcel {

    @XmlElement(name = "Area", required = true)
    protected TArea area;
    @XmlElement(name = "Encumbrance", required = true)
    protected TEncumbrance encumbrance;
    @XmlElement(name = "EntitySpatial")
    protected TEntitySpatialZUInp entitySpatial;
    @XmlElement(name = "Contours")
    protected TContoursSubParcel contours;

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link TArea }
     *     
     */
    public TArea getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link TArea }
     *     
     */
    public void setArea(TArea value) {
        this.area = value;
    }

    /**
     * Gets the value of the encumbrance property.
     * 
     * @return
     *     possible object is
     *     {@link TEncumbrance }
     *     
     */
    public TEncumbrance getEncumbrance() {
        return encumbrance;
    }

    /**
     * Sets the value of the encumbrance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEncumbrance }
     *     
     */
    public void setEncumbrance(TEncumbrance value) {
        this.encumbrance = value;
    }

    /**
     * Gets the value of the entitySpatial property.
     * 
     * @return
     *     possible object is
     *     {@link TEntitySpatialZUInp }
     *     
     */
    public TEntitySpatialZUInp getEntitySpatial() {
        return entitySpatial;
    }

    /**
     * Sets the value of the entitySpatial property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEntitySpatialZUInp }
     *     
     */
    public void setEntitySpatial(TEntitySpatialZUInp value) {
        this.entitySpatial = value;
    }

    /**
     * Gets the value of the contours property.
     * 
     * @return
     *     possible object is
     *     {@link TContoursSubParcel }
     *     
     */
    public TContoursSubParcel getContours() {
        return contours;
    }

    /**
     * Sets the value of the contours property.
     * 
     * @param value
     *     allowed object is
     *     {@link TContoursSubParcel }
     *     
     */
    public void setContours(TContoursSubParcel value) {
        this.contours = value;
    }

}
