//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 09:42:06 AM MSK 
//


package ga.osipov.XSD.MP_v06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Вычисления
 * 
 * <p>Java class for tTochnSurvey complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTochnSurvey"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CadastralNumberDefinition" type="{}sNe50"/&gt;
 *         &lt;element name="Formula" type="{}sNe4000"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTochnSurvey", propOrder = {
    "cadastralNumberDefinition",
    "formula"
})
@XmlSeeAlso({
    ga.osipov.XSD.MP_v06.MP.Survey.TochnAreaParcels.TochnAreaParcel.class,
    TTochnSurveySubParcel.class
})
public class TTochnSurvey {

    @XmlElement(name = "CadastralNumberDefinition", required = true)
    protected String cadastralNumberDefinition;
    @XmlElement(name = "Formula", required = true)
    protected String formula;

    /**
     * Gets the value of the cadastralNumberDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadastralNumberDefinition() {
        return cadastralNumberDefinition;
    }

    /**
     * Sets the value of the cadastralNumberDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadastralNumberDefinition(String value) {
        this.cadastralNumberDefinition = value;
    }

    /**
     * Gets the value of the formula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormula() {
        return formula;
    }

    /**
     * Sets the value of the formula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormula(String value) {
        this.formula = value;
    }

}
